### ISSUE TITLE
read/write restart file, ensemble generation step

### ISSUE THREAD

**Issue by jkuang-exploro** [NOAA-EMC/godas#101]
The app is complaining some netCDF file couldn't be found.

FATAL from PE     0: NETCDF ERROR: No such file or directory File=RESTART/MOM.res.nc

This is likely in a write process where the model need to output RESTART file while cannot find the folder and file identifier.

**Comment by guillaumevernieres** [comment]
@JianKuang-NOAA : You need to give more context. What case were you running? At what step did it fail?
MOM needs a RESTART directory to be created in order to run, it looks like that step was omitted in whatever that is you are testing.
