### ISSUE TITLE
Switch to default compiler (intel 18)

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#106]

**Comment by flampouris** [comment]
Hera helpdesk is informed that the HDF5 is not compiled with mpi.

**Comment by flampouris** [comment]
The develop branch of SOCA passes all the tests with the default installations of the Intel (18), and default parallel NetCDF, supported by Hera IT. 

To use it, load the following module:

/scratch2/NCEPDEV/marine/marineda/modulefiles/jedi-18.0.5.274

**Comment by guillaumevernieres** [comment]
April's fool! In October ... I don't understand. :)
Nice @flampouris thanks for pushing them!
