### ISSUE TITLE
Presence of raw sst obs not checked properly

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#121]
**Observed failure**
The scripts marks avhrr19 as being present in the raw obs directory while it is not for 10/22. Failure happens when trying to list the none existing files. 

**How to reproduce**
Run the 3dvar with the start/end date:
SDATE: 2011-10-22t12:00:00
EDATE: 2011-10-22t12:00:00

**Comment by guillaumevernieres** [comment]
@ShastriPaturi : Also, adding -O when calling ncks will allow debugging without having to manually remove the obs files in the scratch directory.

**Comment by ShastriPaturi** [comment]
@guillaumevernieres,
I Run the 3dvar succesfully with the start/end date:
SDATE: 2011-10-22t12:00:00
EDATE: 2011-10-22t12:00:00

I did not see the **Observed failure** that you see.

My log files are at: /scratch2/NCEPDEV/marine/Shastri.Paturi/WORKFLOW_QCexp/workflowtestSST/log/2011102212
In the obs_prep.log file, the message regarding avrhrr19 is misleading. I will fix it.

**Comment by flampouris** [comment]
@guillaumevernieres where is your log file?

**Comment by guillaumevernieres** [comment]
Humm, weird. I'll look into it some more. I'm running a few experiments right now, so I'm not touching my sandbox for a while.

You've got a few 100 of them to chose from:
/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/runs/test06/log/2011102212/obs_prep.log.0
Around line 73:
*SST Observations from sst.avhrr_l3u.nesdis-AVHRR19 for 20111022 exist and will be processed, obs directory: /scratch2/NCEPDEV/marine/marineda/oce\
an_observations/data/sst.avhrr_l3u.nesdis/20111022                                                                                                
ls: cannot access *AVHRR19*.nc: No such file or directory*

**Comment by flampouris** [comment]
- The error is reproducible under conditions. 

- The solution is to check for the existence of at least one $sat file and not only for the existence of the expected directory containing the observations.

**Comment by ShastriPaturi** [comment]
> * The error is reproducible under conditions.
> * The solution is to check for the existence of at least one $sat file and not only for the existence of the expected directory containing the observations.

Under what conditions - please specify.
