### ISSUE TITLE
rundir  has FirstName.LastName twice

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/godas#125]
The run directory structure is typically: 
/scratch1/NCEPDEV/stmp2/Jessica.Meixner/Jessica.Meixner/rundir/workflowtest001
so 
/some/path/to/tmp/FirstName.LastName/FirstName.LastName/rundir/<nameofworkflow> 

Why do we have FirstName.LastName twice?

**Comment by flampouris** [comment]
Oh man, we have fixed this thing 2-3 times till now, let this be the last one...

To answer @JessicaMeixner-NOAA 's question, we expand the temporary paths at the definitions of the "base" by the $USER which is already included at the *term_temp.
