### ISSUE TITLE
Access to NDATE and NHOUR in scripts

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/godas#126]
In the workflow/platforms/hera.yaml (in the feature/addmodel) branch I added: 
```
  # NWPROD - location of the NCEP operational "nwprod" directory, which
  # only has meaning on the NCEP WCOSS machines.  It is used to get
  # the paths to certain programs and scripts.
  NWPROD: "/scratch1/NCEPDEV/global/glopara"

  config_base_extras: !expand |
    export NDATE="$NWPROD/git/NCEPLIBS-prod_util/v1.1.0/exec/ndate"
    export NHOUR="$NWPROD/git/NCEPLIBS-prod_util/v1.1.0/exec/nhour"
```
However, when trying to use NHOUR or NDATE in a script (for example in scripts/prep_forecast.sh in the feature/addmodel branch) this variable would be undefined.  I currently got around this by hard-coding NHOUR to the above path directly in this script, but I'm not sure why it can't be set in this platform dependent file and then used in the script.

**Comment by flampouris** [comment]
@JessicaMeixner-NOAA Check the workflow/config/base.yaml, probably you need to add them there.
