### ISSUE TITLE
checkout.sh or README needs updating

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/godas#132]
If you follow the README step-by-step, you will attempt to clone the soca-bundle twice as it's cloned in the checkout.sh script and in step 0.  We should remove one or the other. Preference on which one to remove? @guillaumevernieres  @flampouris    I can make a PR with whichever removed or if someone has one coming up they can add that to theirs.

**Comment by guillaumevernieres** [comment]
@JessicaMeixner-NOAA : Thanks for spotting that! Sure, issue a pr.

**Comment by JessicaMeixner-NOAA** [comment]
@guillaumevernieres   Do you want it left in the checkout.sh script (we could even add the LETKF @flampouris ) or do you want people to do it explicitly?

**Comment by flampouris** [comment]
I vote for all the checkout actions to be bundled.
