### ISSUE TITLE
Issues with MOM6Tools

### ISSUE THREAD

**Issue by flampouris** [NOAA-EMC/godas#141]
@jkbk2004 and @ShastriPaturi 

This is a list of identified issues of the current version of the mom6tools. 

Please modify this message of issues that have to be tackled for the next PR.

- During the installation, the tools should be copied to the [...]/build/bin/
- Update the examples at readme, according to the GODAS.  
- To be called at the Post-processing

**Comment by jkbk2004** [comment]
@flampouris and @ShastriPaturi yes, src/mom6-tools.plot/*.py should be copied or linked in build/bin.

**Comment by jkbk2004** [comment]
included mom6-tools inside workflow.
