### ISSUE TITLE
Cannot copy pre-processed files into ${GODAS_RC}/ioda_observations

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/godas#149]
The pre-processed ioda.sst.avhrr19_l3u.nesdis.24h.nc file in ${GODAS_RC}/ioda_observations is incomplete for 2011120212. 

The complete set of pre-processed observations for satellite SST exist at /scratch2/NCEPDEV/marine/Shastri.Paturi/ioda_observations/2011120212.

However, the complete files cannot be moved to ${GODAS_RC}/ioda_observations as no write permissions exist.

**Comment by flampouris** [comment]
Please use the marineda role account to update, let me know if there is an
issue. Closing the ticket.

**Comment by ShastriPaturi** [comment]
Thank you.
