### ISSUE TITLE
Prepare forcing files

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#194]
- [ ] GEFS (2000-2019) time stamp needs corrections
- [ ] CFSv2 (2020 to March 2021) 
- [ ] GFS onward

**Comment by hyunchul386** [comment]
Currently 
GEFS_DATM update for time stamp has been done  from 2000-01 to 2008-02, and continued.
CFSR_DATM from CFSv2 has been converted from 1980-01 to 2022-02
GFS_DATM has been prepared from 2021-03-22 to 2021-06 and continued

**Comment by guillaumevernieres** [comment]
> Currently GEFS_DATM update for time stamp has been done from 2000-01 to 2008-02, and continued. CFSR_DATM from CFSv2 has been converted from 1980-01 to 2022-02 GFS_DATM has been prepared from 2021-03-22 to 2021-06 and continued

Thanks for the info @hyunchul386 , do you have an estimate of when the forcing mentioned here will be processed?

**Comment by hyunchul386** [comment]
@guillaumevernieres, I think
GEFS_DATM would be completed the process for 2009-12, in two weeks from now.
GFS_DATM would be estimated for the process for 2021-03, in three weeks from now.
CFSR_DATM is now in near-real time process with one-month delay.

**Comment by hyunchul386** [comment]
Just update for current status of DATM forcing files:
GEFS_DATM would be completed the process for 2014-12, in two weeks from now.
GFS_DATM would be estimated for the process for 2021-09, in two weeks from now.
CFSR_DATM is now in near-real time process with one-month delay.

**Comment by hyunchul386** [comment]
Update  for current status of DATM forcing files:
GEFS_DATM has been completed for the period of 2000-01 ~ 2019-12, 
    the new updated data will be replaced to the previous data after announcements.
GFS_DATM has been generated for 2021-12, and would be completed in a week from now.
CFSR_DATM is now in near-real time process with one-month delay.

**Comment by hyunchul386** [comment]
Updates for current status of DATM forcing files:
GEFS_DATM :  the updated data in HPSS currently is in /5year/NCEPDEV/marineda/DATM_INPUT/GEFS_new
                       this will be replace to /5year/NCEPDEV/marineda/DATM_INPUT/GEFS, sooner or later.
                       let me know if you have any issue in this replacement. The GEFS data in Orion is also considering to be replaced 
                       by the updated one.
GFS_DATM : the GFS_DATM data at HPSS is archived at /5year/NCEPDEV/marineda/DATM_INPUT/GFS
                     at Orion, the some GFS_DATM data is saved at /work/noaa/ng-godas/marineda/DATM_INPUT/GFS/
                     The code and scripts of GFS_DATM  conversion in Niagara are at /collab1/data/Hyun-Chul.Lee/GFS/

CFSR_DATM : the CFSR_DATM data at HPSS is archives at /5year/NCEPDEV/marineda/DATM_INPUT/CFSR/

**Comment by hyunchul386** [comment]
Updates for current status of DATM forcing files:
GEFS_DATM :  20 year (2000-01 ~ 2019-12) update has been done. Keep the previous data until June 30, as is.
GFS_DATM : Update for 2021-01 ~ 2022-02 has been done, in near real time
CFSR_DATM : in near retime

**Comment by hyunchul386** [comment]
Updates for current status of DATM forcing files:
GEFS_DATM : 20 year (2000-01 ~ 2019-12) update has been done. Keep the previous data until June 30, as is.
GFS_DATM : 2021-01 ~ 2022-03 has been done, in near real time
CFSR_DATM : 1980-01 ~ 2022-03 has been done,  in near real time

**Comment by guillaumevernieres** [comment]
closing, redundant with #213
