### ISSUE TITLE
Real time processing of observation

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#206]
Write the necessary software/scripting tools to fetch the real time observations.

**Comment by guillaumevernieres** [comment]
Who is working on this issue @ShastriPaturi ?

**Comment by guillaumevernieres** [comment]
How is that work going @ShastriPaturi ?

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, the script to fetch obs and run ioda-converters has been tested for ADT with a cron job on orion.
I am working on the rest. Will push the scripts to a feature branch when SST: OSTIA, insitu: FNMOC and icec: NSIDC CDR are tested.

**Comment by guillaumevernieres** [comment]
Should have been closed with #209
