### ISSUE TITLE
Process FNMOC observations from Jan 2015 to ~present

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#207]
Develop converter, process obs for 2015-present(ish), provide a yaml configuration and move to R2D2: 
- [x] Argo, Moorings, CTD, XBT (FNMOC)
- [x] Ship (FNMOC)
- [x] Trak FNMOC

**Comment by guillaumevernieres** [comment]
@ShastriPaturi , can you have a look at the above list and add what's missing?

**Comment by guillaumevernieres** [comment]
@ShastriPaturi , @YanHao-NOAA I see the FNMOC "profile" are in R2D2. Thanks for doing this. 
- Was it tested?
- @YanHao-NOAA has the markdown table been converted to a google sheet/doc and updated with what's available in the benchmark_v2 database?
- Could the same thing be done for ship and track?

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, I have not tested it yet.

**Comment by guillaumevernieres** [comment]
I think this is done ... closing.
