### ISSUE TITLE
Observation sanity check: Obs count, missing files

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#212]
Write a python script that will return a plot of the obs count of a list of ioda files.
Input: A path to ioda files
Ouput: A plot of numver of obs vs date

As a first step, the api would look something like this:

Example: 
``godas_obssanitycheck.py --file_descriptor adt_c2 --path </path/to/ioda/files>``

**Comment by mjhossen** [comment]
I wrote a python script using a class to find missing files, to plot number of observations and min/max value of a variable, such as absolute_dynamic_topography. The path of the file is 
/work/noaa/ng-godas/jhossen/s2s_sprint_apr23
The command is 
python godas_obssanitycheck.py -v nlocs -o obscount -f adt_c2 -d 20150101 20150130 -g ObsValue

**Comment by mjhossen** [comment]
![minmax_adt_c2_2015](https://user-images.githubusercontent.com/65732322/161980741-32725861-5092-4ecc-9171-1e4e0ddc8f47.png)
![nloc_adt_c2_2015](https://user-images.githubusercontent.com/65732322/161980911-ef36b42f-5215-47ca-8835-e28f15f05776.png)

**Comment by guillaumevernieres** [comment]
for date interval, use: ``--start`` (or `-s`)and ``--end`` (or `-e`).

**Comment by guillaumevernieres** [comment]
@mjhossen look here for the r2d2 database:
```console
/work/noaa/marine/marineda/r2d2/obs/jcsda_soca/ob/benchmark_v2/
```

**Comment by guillaumevernieres** [comment]
Closing this issue. @mjhossen provided a first prototype. Refinement will be addressed in separate issues.
