### ISSUE TITLE
Preparing Forcing for S2S

### ISSUE THREAD

**Issue by hyunchul386** [NOAA-EMC/godas#213]
Preparing surface flux forcing for S2S runs

**Comment by hyunchul386** [comment]
DATM forcing for S2S runs

-----------------------------------------------------------------------------------------------------

**PSL** [ 2019-05-01 ~ 2020-11-30 ]  : **GEFS_new + CFSR**
       - GEFS_new :  2019-05-01 ~ 2019-12-31
       - currently HPSS
       - will be ported to Orion :  /work/noaa/ng-godas/marineda/DATM_INPUT/GEFS_new

       - CFSR : 2020-01-01 ~ 2020-11-30
       - saved at Orion :  /work/noaa/ng-godas/marineda/DATM_INPUT/CFSR

**EMC-1** [2021-12-01 ~ 2022-05-01] : **GFS**
       - GFS : 2021-12-01 ~ 2022-05-01 
       - currently HPSS
       - will be ported to Orion :  /work/noaa/ng-godas/marineda/DATM_INPUT/GFS

**EMC-2** [2021-06-01 ~ 2021-11-30] : **GFS** 
       - CFSR : 2021-06-01 ~ 2021-11-30 
       - currently HPSS
       - will be ported to Orion :  /work/noaa/ng-godas/marineda/DATM_INPUT/GFS

**EMC-3** [2020-12-01 ~ 2021-03-01] : **CFSR**
       - CFSR : 2020-12-01 ~ 2021-03-01 
       - saved at Orion :  /work/noaa/ng-godas/marineda/DATM_INPUT/CFSR

**EMC-4** [2020-06-01 ~ 2020-11-30] : **CFSR**
       - CFSR : 2020-06-01 ~ 2020-11-30
       - saved at Orion :  /work/noaa/ng-godas/marineda/DATM_INPUT/CFSR

-----------------------------------------------------------------------------------------------------

GFS ; [EMC-1/2] : 713Gb
         2021-06-01 ~ 2022-05-01

GEFS_new ; [Test, PSL]  : 300Gb
          2015-01-01 ~ 2015-12-31
          2019-05-01 ~ 2019-12-31

CFSR ; [PSL + EMC-3/4] ; 144 Gb ; currently on Orion.
         2020-01-01 ~ 2021-03-01
         
==> additional spaces of  about 1Tb         
         
-----------------------------------------------------------------------------------------------------

Another Runs for 2016 - 2018

GEFS_new ==> about 576 GB

-----------------------------------------------------------------------------------------------------

**Comment by hyunchul386** [comment]
A sanity check of GFS/CFSR

![datm_zonal_CFSR_GFS_2021033112](https://user-images.githubusercontent.com/14810515/161844044-2b29760a-0b3a-485e-96d8-de67bde7ce58.gif)

**Comment by guillaumevernieres** [comment]
Thanks @hyunchul386 . Can you replace your above plot by a higher resolution version? I can't read the legend. Could you push your plotting scripts to this repo as well?

**Comment by hyunchul386** [comment]
@guillaumevernieres The scripts can be found https://github.com/hyunchul386/godas/tree/feature/gfs2datm/DATM_FORCING/DATM_Sanitycheck

**Comment by hyunchul386** [comment]
All of following data has been transferred to Orion

GFS ; [EMC-1/2] 
2021-06-01 ~ 2022-05-01

GEFS_new ; [Test, PSL] 
2015-01-01 ~ 2015-12-31
2019-05-01 ~ 2019-12-31

CFSR ; [PSL + EMC-3/4] 
2020-01-01 ~ 2021-03-01

**Comment by hyunchul386** [comment]
Sanity checks
![datm_zonal_CFSR_GFS_2021071512](https://user-images.githubusercontent.com/14810515/162512588-d9976de6-4f8b-4c7a-ad1a-e04620cff4b0.gif)
![datm_zonal_CFSR_GFS_2021091512](https://user-images.githubusercontent.com/14810515/162512684-308c67c3-7ddc-4478-968f-d9edc8c7e50f.gif)
![datm_zonal_CFSR_GEFS_new_2015011512](https://user-images.githubusercontent.com/14810515/162512769-15396eb9-9c93-4b09-824a-56c0af88b4de.gif)
![datm_zonal_CFSR_GEFS_new_2015061512](https://user-images.githubusercontent.com/14810515/162512824-cef762c1-5165-4d64-94c0-a2d2bc82d773.gif)
![datm_zonal_CFSR_GEFS_new_2015121512](https://user-images.githubusercontent.com/14810515/162512908-bcdceaab-df1b-4050-a2b5-fa0eb013b60b.gif)

**Comment by guillaumevernieres** [comment]
It seems under control ... Closing this issue @hyunchul386 . We'll open a new one if need be.
