### ISSUE TITLE
Move/convert the EMC icec  ng-godas obs to R2D2

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#215]
waiting for  #212

**Comment by ShastriPaturi** [comment]
The path to the ioda-v2 obs for EMC icec (2015-2020) is:
/work/noaa/ng-godas/spaturi/nggodas_realtime_ext/ng-godas/obs/ioda-v2/icec

**Comment by ShastriPaturi** [comment]
The 2021 EMC icec for 2021 is at:
/work/noaa/ng-godas/spaturi/icel2_emc_2021.

The SSMI instrument died on 20210809. No more SSMI data.

**Comment by ShastriPaturi** [comment]
The EMC ICEC IODA-v2 data (2015-2020) have been moved to R2D2 at its new location:
**/work/noaa/ng-godas/r2d2/gdas_marine/ob/s2s_v1**

@guillaumevernieres, the issue can be closed.
