### ISSUE TITLE
Move/convert the SSS ng-godas obs to R2D2

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#216]

**Comment by ShastriPaturi** [comment]
The path to the ioda-v2 obs for SSS (2015-2020) is:
/work/noaa/ng-godas/spaturi/nggodas_realtime_ext/ng-godas/obs/ioda-v2/sss

**Comment by YanHao-NOAA** [comment]
I copied three days (2015-04-01  to  2015-04-03) sss_smap and sss_smos data in R2D2: e.g. /work/noaa/marine/marineda/r2d2/obs/jcsda_soca/ob/benchmark_v2/P1D/2015-04-01/jcsda_soca.benchmark_v2.ob.P1D.sss_smos_esa.2015-04-03T00:00:00Z.nc4  and jcsda_soca.benchmark_v2.ob.P1D.sss_smap_jpl.2015-04-03T00:00:00Z.nc4, please let me know if it is okay to move forward to transfer all sss files ( we have data 20150101-20200731).

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, the SSS IODA-v2 (2015-2020) data have been moved to R2D2 at its new location:
**/work/noaa/ng-godas/r2d2/gdas_marine/ob/s2s_v1**

The issue can be closed.

**Comment by guillaumevernieres** [comment]
Feel free to close it next time @ShastriPaturi
