### ISSUE TITLE
Download AVHRR SST's in multiple streams

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#217]

**Comment by guillaumevernieres** [comment]
FYI @ShastriPaturi , I'm downloading a few days of viirs npp.

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, downloading AVHRR from NESDIS, 3 streams: 2015, 2016, 2017.
Orion performance: (6 months: ~12 hrs). NOAA18 and NOAA19 (10 min files)
/work/noaa/ng-godas/spaturi/nggodas_realtime_ext/DATA_realtime/cron/sst.avhrr_l3u.nesdis/

**Comment by guillaumevernieres** [comment]
Thanks @ShastriPaturi . Can you re-prioritize the download like this:
2019-2022 
2015
2016-2018 (bonus points)

**Comment by ShastriPaturi** [comment]
@guillaumevernieres.
I will let the current download continue and start the download from 2019-2022 on a separate stream.

**Comment by guillaumevernieres** [comment]
Also, create the same issue for viirs @ShastriPaturi .

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres, downloading AVHRR from NESDIS, 3 streams: 2015, 2016, 2017. Orion performance: (6 months: ~12 hrs). NOAA18 and NOAA19 (10 min files) /work/noaa/ng-godas/spaturi/nggodas_realtime_ext/DATA_realtime/cron/sst.avhrr_l3u.nesdis/

We're still missing MetOp @ShastriPaturi ... Any idea where to get those?

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, you read my mind and you are ahead of me. Adding that:

Download MetOp AVHRR SST data from NASA JPL PODAAC server:
https://podaac-tools.jpl.nasa.gov/drive/files/allData/ghrsst/data/GDS2/L3U

Period:
 2019-2022
 2015
 2016-2018

**Comment by ShastriPaturi** [comment]
The AVHRR SST (NOAA18,19, MetOp-<A,B,C>) are downloaded from 2015-2022 (realtime)
/work/noaa/ng-godas/spaturi/nggodas_realtime_ext/DATA_realtime/cron/sst.avhrr_l3u.nesdis/
