### ISSUE TITLE
Move/convert the ADT ng-godas obs to R2D2

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/godas#218]
Download and convert ADT observations that use the egm2008 MDT from 2015 to 2022.

**Comment by ShastriPaturi** [comment]
The path to the ioda-v2 obs for ADT (2015-2020) is:
/work/noaa/ng-godas/spaturi/nggodas_realtime_ext/ng-godas/obs/ioda-v2/adt

**Comment by guillaumevernieres** [comment]
@ShastriPaturi , I'm moving your files to the benchmarkv2 database. Once done I'll have to rename ``obs_absolute_dynamic_topography`` to ``absolute_dynamic_topography`` . I'll close the issue after that.

**Comment by guillaumevernieres** [comment]
@ShastriPaturi ,looks like Jan 2019 is missing, also, some have been renamed or created with a newer converter ... 
As of now we have 2015-2018, missing Jan 2019, Feb 2019 to Dec 2020

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, for Jan 2019, data is missing till Jan 27. Feb 2019 to Dec 2020, ioda-ve files are available:
/work/noaa/ng-godas/spaturi/nggodas_realtime_ext/ng-godas/obs/ioda-v2/adt

**Comment by ShastriPaturi** [comment]
A new satellite: SENTINEL 6A is added from 20220111.
Also, the adt_xgm2016 is removed from 20220116/rads_adt_<sat>_YYYYJDAY.nc and only adt_egm2008 is being retained.
WCOFS team at NOS has found the geoid egm2008 better than xgm2016.

The rads_adt2ioda.py has been updated to read adt_egm2016.
Re-converting from 2015-20220314 with name: adt_<sat>_egm2008_YYYYMMDD.nc
/work/noaa/spaturi/nggodas_realtime_ext/ng-godas/obs/ioda-v2/adt

The links: 
"ftp://ftp.star.nesdis.noaa.gov/pub/sod/lsa/rads/adt" and 
"https://ww.start.nesdis.noaa.gov/pub/sod/lsa/rads/adt/" 

are not accessible on orion.
ADT data from NCEP data tanks for 2022 (Jan & Feb) have been saved on hera.

**Comment by guillaumevernieres** [comment]
``soca_store_obs.py --start 20150101 --end 20211231 --source ./obs/adt --provider jcsda_soca --experiment benchmark_v2 --obstype adt --platforms 3a_egm2008 3b_egm2008 c2_egm2008 j2_egm2008 j3_egm2008 sa_egm2008``

Copying to `benchmark_v2``. @ShastriPaturi , am I missing an instrument from the list above?

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, you are not missing an instrument yet. I have completed till 2021. Running 2022 now till 20220314.
SENTINEL 6A is available from 20220111, as mentioned yesterday,

**Comment by guillaumevernieres** [comment]
Looks like your conversion is complete @ShastriPaturi , can you confirm?

**Comment by guillaumevernieres** [comment]
I'm too impatient ... Here's the next copy to R2D2, with 6a added:
``soca_store_obs.py --start 20220101 --end 20220314 --source ./obs/adt --provider jcsda_soca --experiment benchmark_v2 --obstype adt --platforms 3a_egm2008 3b_egm2008 c2_egm2008 j2_egm2008 j3_egm2008 sa_egm2008 6a_egm2008``

**Comment by guillaumevernieres** [comment]
I'm closing this issue @ShastriPaturi ! Your converted obs are in R2D2.
