### ISSUE TITLE
Check the 10mn sst obs

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#226]
Run the basic check that @mjhossen developed on the ioda files that are staged to be moved to r2d2 eventually:
```console
/work/noaa/marine/Guillaume.Vernieres/OBS/sprint1of4/convert2ioda/scratch/ioda_data
```
the above should contain `noaa18` and `noaa19` sst retrievals .

**Comment by mjhossen** [comment]
Updated godas-obsssanitycheck.py for the ioda files. Please see the attached. 
![Screen Shot 2022-04-11 at 7 52 50 AM](https://user-images.githubusercontent.com/65732322/162754707-d4fc61bb-b0f9-4d64-b8de-04d2e13e509f.png)
