### ISSUE TITLE
Obs database inventory

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#229]
Write python based tools to generate an inventory of the database. 

**Input:**
- A list of obstype (`adt`, `sst`, `sss`, `icec`, ...), or maybe we simply get the full list from the DB
- path to an r2d2 database

**Output:** 
- A complete detailed report of the list of platforms/instruments available from the database for the obs type specified in the input, along with the date range of availability   

That could be organized in "barplots" maybe? Something like that:

![inventory-obsdb](https://user-images.githubusercontent.com/14031856/163024387-d143c5a4-83d0-4d11-af42-f10997cf0f4e.png)

**Comment by mjhossen** [comment]
Produce a preliminary figure. It shows there is no data for adt_3a and adt_j3 between Jan 01 2015 to Dec 31, 2015. Also few dates are missing for adt_c2.
![Screen Shot 2022-04-14 at 7 16 16 AM](https://user-images.githubusercontent.com/65732322/163401428-34b37154-8a56-43df-8440-b3492813effc.png)

**Comment by guillaumevernieres** [comment]
Looks good @mjhossen . Could you do the same fot the other platforms/instruments? And maybe for a wider time interval, say, 2015-2022. 
 I don't think the "Obs_type" legend is necessary.

**Comment by mjhossen** [comment]
Here is the file from 2015 to 2022. I tried to remove y label, then I cannot see any file_descriptor, only some numeric number. It seems it is hard to put the text inside the box that you wants.
![Screen Shot 2022-04-14 at 10 25 20 AM](https://user-images.githubusercontent.com/65732322/163432675-2ea08263-a659-4b56-907f-cf67d5c61843.png)

**Comment by mjhossen** [comment]
Please see the full report. Still I can improve it.
![Screen Shot 2022-04-14 at 10 39 39 AM](https://user-images.githubusercontent.com/65732322/163436596-d98f65cf-78f3-4516-889a-95747dbc789f.png)

**Comment by mjhossen** [comment]
Latest one. I think this shows us what we have and what are missing.
![Screen Shot 2022-04-14 at 12 06 01 PM](https://user-images.githubusercontent.com/65732322/163450816-3bf7e919-816d-4fed-9e60-960215b974c6.png)

**Comment by guillaumevernieres** [comment]
Thanks @mjhossen . That is very useful! 
Repeating what I said on slack, but let try to post the comments related to this issue here instead of slack.
- Remove the y-label (file_descriptor), I think we know what it is
- Replace the title by something relevant to what inventory you are making, something like: `gdas_marine` `s2s_v1` `P1D files` (P1D because it looks like you are only making an inventory of the 24 hour files)
-  Can you produce a similar plot but for the `PT10M` side of the database? This is where all the sst stuff is

**Comment by ShastriPaturi** [comment]
@mjhossen, we are missing adt_3b.
Thanks for doing this. Concur with @guillaumevernieres.
I have populated the r2d2 db with missing adt files from 2019-01 to 2019-07.

**Comment by guillaumevernieres** [comment]
copy paste from @mjhossen 's slack post:

![image](https://user-images.githubusercontent.com/14031856/163471071-1cd4dcfc-25ce-4a32-9e75-1d99c9a7ba88.png)

Looks good but reread my post with the comments above, we're still missing the info of what it is we are making an inventory of.

**Comment by mjhossen** [comment]
Title is corrected and y-axis label is removed. All the observation types are added as suggested. Also order is maintained as Shastri suggests. adt_3b is added too!

![Screen Shot 2022-04-14 at 3 01 27 PM](https://user-images.githubusercontent.com/65732322/163474731-609bb7be-735d-42ae-8e96-647d9f70caff.png)

**Comment by ShastriPaturi** [comment]
@mjhossen sss_smos data is populated for 2015.

**Comment by mjhossen** [comment]
Yes. I checked sss_smos is there. Don't you think?

**Comment by mjhossen** [comment]
Or shouldn't it be there?

**Comment by ShastriPaturi** [comment]
@mjhossen, some data were not populated. Now they are.

**Comment by mjhossen** [comment]
I think the script is completed. Now I push in in the feature/obssanitycheck_new. 
It can be closed.
