### ISSUE TITLE
Sanity check of forcing files

### ISSUE THREAD

**Issue by hyunchul386** [NOAA-EMC/godas#231]
Sanity check code of DATM forcing files in python

**Comment by hyunchul386** [comment]
Sanity check of CFSR/GFS at 2021071512 by the developing tool
![CFSR_GFS_2021071512](https://user-images.githubusercontent.com/14810515/163234115-d98db898-10e5-47aa-b86a-735521cca553.png)

**Comment by hyunchul386** [comment]
PR for godas repo

**Comment by hyunchul386** [comment]
Checks for 2021061512, 2021071512, 2021081512 by the clean-up code

![CFSR_GFS_2021081512](https://user-images.githubusercontent.com/14810515/163853041-ebe57efb-2739-42e3-b05e-55807bd21cec.png)

![CFSR_GFS_2021061512](https://user-images.githubusercontent.com/14810515/163852982-55d44e8f-8e82-4c9b-8a9b-8e66f5c76b89.png)

![CFSR_GFS_2021071512](https://user-images.githubusercontent.com/14810515/163853021-60f6d84a-8ed9-4421-949d-a524c9c82063.png)

**Comment by guillaumevernieres** [comment]
should have been closed with the PR ...
