### ISSUE TITLE
Test GFS forcing

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#234]
Test within the UFS framework

**Comment by guillaumevernieres** [comment]
@hyunchul386 , is that something you can do?

**Comment by hyunchul386** [comment]
@guillaumevernieres Working on it

**Comment by hyunchul386** [comment]
@guillaumevernieres Does the recent SOCA workflow use UFS p7 or p8?

**Comment by guillaumevernieres** [comment]
I think @ShastriPaturi is testing as well.

**Comment by ShastriPaturi** [comment]
First Step: @guillaumevernieres and @hyunchul386, tested the DATM_GFS forcing for 1 month (2021-06) forecast from the ufs-weather-model (March 22, 2020 develop branch) RT test.

**Comment by hyunchul386** [comment]
@guillaumevernieres and @ShastriPaturi,  I am working on the test of UFS with GFS from 2021-03-22

**Comment by guillaumevernieres** [comment]
assuming this is done.
