### ISSUE TITLE
Typo in adt copernicus filename

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#250]
There's a typo in the name of the copernicus adt files. It should be `l4` instead of `14`.

Hard to see, but for example, 
``gdas_marine.s2s_v1.ob.P1D.adt_coper14.2015-02-02T00:00:00Z.nc4``
should be:
``gdas_marine.s2s_v1.ob.P1D.adt_coperl4.2015-02-02T00:00:00Z.nc4``

**Comment by ShastriPaturi** [comment]
Updated the r2d2 DB with the corrected adt_coperl4 filename for 2015-2016.
