### ISSUE TITLE
SSMI & SSMIS for 2021 in R2D2

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#253]
- [x] Convert 2 `ioda`  (@mjhossen , @hyunchul386 )
- [x] Move to R2D2 (@ShastriPaturi )

**Comment by mjhossen** [comment]
Completed the conversion of ssmi data (2021) into ioda format. Now ready for moving to R2D2 database.

**Comment by guillaumevernieres** [comment]
I think we're done ...
