### ISSUE TITLE
Ocean & sea-ice monitoring: Generate and organize surface plots

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#271]
### Generate png figures for:
Develop a "script" python or/and shell that will generate the following fiures:
- Background states: `sss`, `sst`, `ssh`, `aicen` & `hicen` with the 3 following projection
     - Global projection (pick your favorite one)
     - North polar stereo
     - South polar stereo
- Obs-spaces: png figures of the omb's for each observation space assimilated 

### Organization

This is what an experiment directory looks like right now:
```console
.
├── ana
├── bkg
├── cycle.sh -> ../soca-science/scripts/workflow/cycle.sh
├── cycle_status
├── exp.config
├── godas
├── incr
├── logs
├── obs_out
├── rst
├── SCRATCH
└── static
```
After running that script, we would like to see an added `monitoring` directory:
```console
.
├── ana
├── bkg
├── cycle.sh -> ../soca-science/scripts/workflow/cycle.sh
├── cycle_status
├── exp.config
├── godas
├── incr
├── logs
├── monitoring
├── obs_out
├── rst
├── SCRATCH
└── static
```
which should be organized as follows for example:
```console
── monitoring
│   └── 2020
│       ├── 2020120100
│       │   └── bkg
│       │       ├── sst.global.2020120100.png
│       │       └── sss.global.2020120100.png
│       │       └── ssh.global.2020120100.png
│       │       └── aicen.north.2020120100.png
│       │       └── aicen.south.2020120100.png
│       │       └── hicen.north.2020120100.png
│       │       └── hicen.south.2020120100.png
│       │       └── sst.north.2020120100.png
│       │       └── sst.south.2020120100.png
│       │       └── sss.north.2020120100.png
│       │       └── sss.south.2020120100.png
│       │       └── ssh.north.2020120100.png
│       │       └── ssh.south.2020120100.png
│       │   └── omb
│       │       ├── sst_metopa_l3u_so025.2020120100.nc
│       │       └── sst_metopb_l3u_so025.2020120100.nc
│       │       └── ...
```
I will provide the tools to plot the `omb`'s , use your existing tools to plot the background state.

**Comment by mjhossen** [comment]
I have completed scripts for plotting state vectors such as bkg, ana etc. You can find the scripts in the folder: /work/noaa/marine/jhossen/Plot_field. There are two scripts: soca_plotfield.sh and soca_plotfield.py. Please read the Readme.md file to run the plot scripts.

**Comment by mjhossen** [comment]
I will include the scripts for ombg which has been provided  by Guillaume.

**Comment by guillaumevernieres** [comment]
> I have completed scripts for plotting state vectors such as bkg, ana etc. You can find the scripts in the folder: /work/noaa/marine/jhossen/Plot_field. There are two scripts: soca_plotfield.sh and soca_plotfield.py. Please read the Readme.md file to run the plot scripts.

copy/paste of my comments on slack:
- You are missing aicen and hicen (north & south)
- color scale for global temp should be ~[-1.8, 32]
- color scale for ssh are saturated too, try something like [-2, 1.3]

**Comment by mjhossen** [comment]
Fixed
