### ISSUE TITLE
Bug fix for adt conversion: "copernicus_l4adt2ioda.py"

### ISSUE THREAD

**Issue by mjhossen** [NOAA-EMC/godas#273]
"copernicus_l4adt2ioda.py" produces a wrong date format, such as 2019-05-09T12:00:00Z" when it should be "2019-05-10T00:00:00Z.
Soca-science produce an empty observation file for adt_coperl4.

**Comment by guillaumevernieres** [comment]
I'm closing this issue, which really belongs in the `ioda-converters` repositories anyways.
Your PR is failing the ci @mjhossen , you need to fix this:
https://github.com/JCSDA-internal/ioda-converters/pull/956
