### ISSUE TITLE
Document the code that generates the forcing

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#276]
A forcing generation step is going to be required within the global workflow. The code provided [here](https://github.com/NOAA-EMC/godas/blob/develop/forc/) is the prototype candidate but lacks documentation and isn't usable or easily understandable by a third party. 
For example, [conv_gfs2datm_long_beta4.f](https://github.com/NOAA-EMC/godas/blob/develop/forc/GFS/conv_gfs2datm_long_beta4.f) is completely void of documentation.

A few comments pointed out by @aerorahul : 

1. precip rate, u/v fluxes are from a 6 hour forecast.
2. radiation etc from 00 hour forecast (still within the IAU window)
3. lowest model thickness is coming from the 00 forecast (EDITED: previously quoted this as analysis)

This seems inconsistent if someone tries to compute balance.

@hyunchul386 , can you document your code and justify your choices?

**Comment by aerorahul** [comment]
I can provide a shell python substitute that can replace the fortran code and the scripts associated with generating the forcings.

In addition to the points in the discussion, it would be good to have documentation on:
1. input variables - what are the variables required in the program
2. output variables - what are the variables being written out to the forcing file
3. any calculations performed inside the fortran code - e.g. bulk formula calculations, delz variable manipulation.

**Comment by hyunchul386** [comment]
I am generating README.md for the descriptions of input output variables and calculations for the fortran code.
if there is some issues in the current code in global work and/or the substitute python code improves the efficiency of calculation time, I think it should be considered.

**Comment by aerorahul** [comment]
@hyunchul386 
There is likely nothing wrong with the code and the scripts.  
The issue is to prepare it for use in the cycled ocean DA framework so users can understand it.
Thank you for taking the time to document and clarify potential points of confusions.

**Comment by hyunchul386** [comment]
@aerorahul Okay, I am preparing the documents for clarifying.
