### ISSUE TITLE
Merged #27 too quickly

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#28]
@JianKuang-NOAA , sorry, I approved and merged your last pr too quickly. 
- You have leftover conflict syntax (places.yml).   
- Whatever you did doesn't seem to work on hera, at least for me. Were you able to test? 

@JianKuang-NOAA , @flampouris : Let's agree that at a minimum we test that the creation of the workflow, on Hera, runs OK (running ./setup_case.sh ...) before we submit a pr.

**Comment by flampouris** [comment]
@guillaumevernieres I agree

**Comment by jkuang-exploro** [comment]
Sorry for that. Not got a chance testing it on Hera yet. I've just test it on Hera and it works after your fixes.

**Comment by guillaumevernieres** [comment]
@JianKuang-NOAA , no worries. Thanks for checking.
