### ISSUE TITLE
Horizontal scales are not the same as what was used in the 40 year reanalysis

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#283]
Because I WILL have forgotten comes Monday: 
Just set this
https://github.com/NOAA-EMC/godas/blob/76f137f3c5a55d1c079b21cee410ab496f0f63f3/soca/soca_staticbinit.yaml#L15

to 0km 
and `min grid mult` to 1.

Pinging people so they can remind me, or better yet test and commit the changes!
@ShastriPaturi , @liuxiao37k , @mjhossen , @hyunchul386 , this problem concerns you too!

**Comment by liuxiao37k** [comment]
@guillaumevernieres So the issue is, with `min value` set to 50.0e3, and `min grid mult` set to 2, all part of the ocean higher than ~25°N/S is dominated by this 50.0e3 number, which is too large of a length scale?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres So the issue is, with `min value` set to 50.0e3, and `min grid mult` set to 2, all part of the ocean higher than ~25°N/S is dominated by this 50.0e3 number, which is too large of a length scale?

yes.
