### ISSUE TITLE
Evaluation of 3D BUMP at 1/4 deg

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#301]
## Description
Document the quality (or lack!) of a 3D BUMP based ocean ice analysis. Compare against:
- [ ] PSL's short reanalysis for the 1/4 deg test
- [ ] EN4 and the 40 year godas reanalysis (over a short period) for the 1 deg. (This work is already done, is that correct @jieshunzhu ?)

**Notes:**
@jieshunzhu has already started that work at 1 deg and found significant improvement compared to the 2D BUMP alternative, with close to no parameter tunning.

**Comment by liuxiao37k** [comment]
@guillaumevernieres we can start evaluating the ensemble based vs. `setscale` based 3D BUMP for 1/4 deg, although both need to be reinitialized and compared again at certain point. I can branch off two additional runs from my ongoing analysis (2D BUMP) using these two approaches.

**Comment by guillaumevernieres** [comment]
Closing this issue. Not exactly tested as what was written in the description, but a few of you have shown that the results are better with bump3d ... So moving on!
