### ISSUE TITLE
Ensemble estimate of the length scale in C

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#302]
## Description
Estimate the decorrelation length scale for all variables from an ensemble of climatological perturbations and use these scales to generate a BUMP correlation operator.

Notes:
- Make use of bump training. It will fit GC99 to sampled correlations on the subgrid and extrapolate to the DA grid (I think that's what it does)
- Generate climatological perturbations from already existing S2S forecast? To be discussed with @liuxiao37k

**Comment by liuxiao37k** [comment]
To summarize the immediate next steps per the discussion on July 22:
1. Generate an ensemble of 10-20 members using a version of the coupled UFS model w/ BGC at 0.25deg:
(i) Generate initial ocean perturbations using soca-science (default yaml parameters to start with);  
(ii) Initialize the coupled UFS model independently (i.e., 1 job card for each run) from each perturbed member; @guillaumevernieres how to initialize the atmosphere and fluxes? For a short run, don't we want to generate perturbations for those, too? If not, I am guessing the oceans are going to converge quickly for the first couple weeks before diverging again?
(iii) Run for 2-3 weeks, document the cost (walltime, storage, etc), monitor the spread, etc.
2. While the batch jobs are running, play with bump training tools w/ existing ctests and understand what those parameters mean.

Anything else?

**Comment by guillaumevernieres** [comment]
@liuxiao37k , wrt point 1-ii : the spread of the atm will saturate pretty quickly, so I wouldn't worry about perturbing the initial conditions

I sent you a pm too @liuxiao37k , but posting here for posterity as well :) ... Alternatively to 1, we could generate an ensemble of perturbations from forecast lag differences, similar to the NMC method. Happy to chat about this. It would be quite a bit less resource intensive than running the coupled ufs ... Food for thoughts.

**Comment by liuxiao37k** [comment]
Strategy change for (1):
(i) Generate a reasonable ocean reanalysis w/ bgc at 0.25deg using DATM, at least a year long. 
(ii) As the reanalysis is running, branch off and initialize sequentially an ensemble of coupled hindcasts w/ bgc using simple time-lag techniques on Day 1, 8, 15, 22 of each month (DF=48, double the frequency or extend into Year 2 if needed; halve the frequency and blame G if being told of using too much resource).
(iii) Run each coupled hindcast for at least a few weeks; routinely check "ensemble" spread as new members are made available.
(iv) Ignore the possible impact of initialization hiccups on derived perturbations.

**Comment by liuxiao37k** [comment]
@guillaumevernieres Some "progress":
1. I was wrong about those soca `parameters_bump_cov_*.ymls` being maintained/updated. No, they are not, and outdated.
2. I updated the ymls using saber ctest ymls as templates, and was able to run.
3. I am still using the regular instead of small grid at this point since small is not that small, and small grid ensemble files are not being generated by prior ctests. With one variable (tocn), execution time ~80 seconds but of course depends on bump parameter settings.
4. I am not sure I know what I am expecting to see. `stddev` seems to be reasonable (see fig below), so I am assuming the ensemble files were read in correctly. `cor_rv` and `cor_hv` are nonsense to me, with computed values both globally universal though changing with depth. Aren't they supposed to be spatially (both horizontal and vertically) variant??
5. I pushed the yml [here](https://github.com/JCSDA-internal/soca/blob/ef63ed96ff09b3a1831de3edbff4a80a58cb6be9/test/testinput/parameters_bump_cov_lct.yml) as an example. I tried to play with bump parameters a bit, but couldn't resolve the nonsense `cor_rv` and `cor_hv`. Does anything in the yml seem absolutely wrong? We don't need ice stuff for the ocean in this case, do we?

<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/181572697-1814e083-0cf7-40ba-b42b-861f7ce5195d.png">

**Comment by guillaumevernieres** [comment]
@liuxiao37k :

1. Not surprised, that test has been commented out for a long while.
3. We'll have to add a "ctest" that interpolates the ensemble members to the coarser grid or just simply generate new members at the needed resolution
4. yes, rh/rv should be spatially varying, `stddev` seems fine
5. We can compare to what we had in these yamls when Orion comes back to life.

I'll arrange a meeting with Benjamin and @travissluka

**Comment by guillaumevernieres** [comment]
As a ref, this is where we left of that work a while back: [bump yaml](https://github.com/JCSDA-internal/soca-science/blob/feature/bump3d-gv/configs/soca/static-b_var-hdiag.yaml.sh)

**Comment by guillaumevernieres** [comment]
@liuxiao37k , could you point me to one of your coupled forecasts that failed?

**Comment by liuxiao37k** [comment]
> @liuxiao37k , could you point me to one of your coupled forecasts that failed?

Yes, give me a few hours this afternoon. Earlier I noticed a version difference between the DATM and coupled executables. I am not sure if that contributed to ice crash typically a few days into the coupled forecasts. I rebuilt the coupled version just to be consistent. I plan to re-test this afternoon and will send you both paths if problem still exists.
One of the old coupled forecasts that failed: /work/noaa/ng-godas/xliu/sandbox/29jul22/ens0
where I made a mistake by using the p7c coupled executable. 

Update: new path: /lustre/f2/dev/ncep/Xiao.Liu/sandbox/09aug2022/cpld_BGC/
new ufs clone and build on Aug 24.

**Comment by liuxiao37k** [comment]
@guillaumevernieres I don't think I know enough about b-matrix to interpret these results, so I am asking for your help:
Please see figure attached blow. This is for `Temp`.
1) this was generated by using a 9-mem ensemble of coupled forecasts, initialized on 1/16/2019, 1/31/2019, ... 05/16/2019 every 15 days, with a 10-day lead time. i.e. the ensemble input is composed of 9 `MOM.res.nc` files for 1/26.2019, 2/10/2019, ... 05/26/2019. Also, I used the soca ctest yaml parameters to do training, except changing `resol` to 20. Looks like `resol` is still too small?
The directory is here: 
```
cd /work/noaa/marine/xliu/pr1/build/soca/test/
```
The command is: 
```
/opt/slurm/bin/srun -n 16 /work/noaa/marine/xliu/pr1/build/bin/soca_error_covariance_training.x testinput/parameters_bump_cov_new.yml
```
2) Coupled forecasts are in hybrid layer, but no vertical remapping was done before bump training. (Can you tell me how exactly to do the remapping? Is subtracting global mean `h` also needed here?)
3) What is the unit of `cor-rh`? They are in the order of 1e6, but I thought your previous plots had a range of [0 250]?
4) How bad is it to use this time-lag method to represent ensemble perturbation?
<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/187762355-d1900d91-07e9-4405-bd3c-f910b9442aa0.png">

**Comment by guillaumevernieres** [comment]
Thanks for the figures @liuxiao37k .

1. I think 20 is fine, but I don't know if it is used when estimating length scales. We need to talk to Benjamin when he gets back from pto.
2. I don'r remember on top of my head but the vertical interpolation can be specified in the "state read" part of the yaml.  I'll dig it out and post the solution here later today.
3. units for `cor-rh` are in meters and "layer index" for `cor-rv`
4. it's da best!

**Comment by guillaumevernieres** [comment]
@liuxiao37k , it looks like that part of the code isn't tested anymore ... Oops.
The `yaml` snippet below for the ensemble part of your `parameters_bump_cov_new.yml` should do the trick ...
```yaml
ensemble:
  members from template:
    template:
      read_from_file: 1
      remap_filename: ./INPUT_large/MOM.res.nc
      date: *date
      basename: ./Data/
      ocn_filename: MOM.res_ens%mem%.nc
      state variables:  [tocn, hocn]
    pattern: '%mem%'
    nmembers: 9
```

**Comment by liuxiao37k** [comment]
First, pinging @ShastriPaturi here for easy follow-up.

> @liuxiao37k , it looks like that part of the code isn't tested anymore ... Oops. The `yaml` snippet below for the ensemble part of your `parameters_bump_cov_new.yml` should do the trick ...

Sorry, the ensemble part should do what trick? Vertical interpolation? @guillaumevernieres

**Comment by guillaumevernieres** [comment]
@liuxiao37k , ~yes,~ all the members will be mapped to the vertical coordinate in `./INPUT_large/MOM.res.nc`

**Comment by liuxiao37k** [comment]
> @liuxiao37k , yes, all the members will be mapped to the vertical coordinate in `./INPUT_large/MOM.res.nc`

Yay! Nice. What about subtracting global mean from `h`? Is it needed? You mentioned something about it yesterday, but I don't remember if it was related to bump training.

**Comment by guillaumevernieres** [comment]
we need to remove the global area weighted mean from `ssh`. It's not in soca yet ... Lets just ignore the issue for now.

**Comment by liuxiao37k** [comment]
some `rh` and `rv` plots here: 
https://drive.google.com/drive/folders/1Qn4riV6LbvGo6HYr--j5jZt956EWoBAC?usp=sharing
It's beyond my expertise to interpret the results for `h`. I cannot tell if we are looking at the effects of `we need to remove the global area weighted mean from ssh` above.
For other states, large effects from eddies/local circulation?
@guillaumevernieres

**Comment by liuxiao37k** [comment]
To revise what I did wrong:
1. initialize forecasts according to the amazing schematic diagram below, to get fcst1, fcst2, ... (n=n_ens);
2. do a `diffstate` call, with vertical remapping, between each lag-pair to generate (n_ens-1) pairs of "difference of states" as pert1 (fcst1-fcst2), pert2 (fcst2-fcst3), ...;
3. repeat what I did but replacing the files below with what come from step 2:
```
ocn_filename: MOM.res_pert%mem%.nc
```
<img width="262" alt="image" src="https://user-images.githubusercontent.com/2281138/191589096-f7749447-b0fd-4c87-a78b-f395bc014432.png">

@guillaumevernieres please confirm. thanks

**Comment by liuxiao37k** [comment]
@guillaumevernieres figures have been updated [link](https://drive.google.com/drive/folders/1Qn4riV6LbvGo6HYr--j5jZt956EWoBAC?usp=sharing)
I still cannot make much sense of these, but I did notice that 1) `h` for all files are now identical; 2) length scales are smaller without temporal variability; 3) magnitude of difference between each pair seems reasonable, e.g. `Temp` has a global mean absolute difference of 0.2-0.3 (example below showing diffstate for 20190406, fcstA initialized on 20190317 - fcstB initialized on 20190401 ).
<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/191654007-2b097a4c-38db-444f-8917-2c236fda2caa.png">

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres figures have been updated [link](https://drive.google.com/drive/folders/1Qn4riV6LbvGo6HYr--j5jZt956EWoBAC?usp=sharing) I still cannot make much sense of these, but I did notice that 1) `h` for all files are now identical; 2) length scales are smaller without temporal variability; 3) magnitude of difference between each pair seems reasonable, e.g. `Temp` has a global mean absolute difference of 0.2-0.3 (example below showing diffstate for 20190406, fcstA initialized on 20190317 - fcstB initialized on 20190401 ). <img alt="image" width="468" src="https://user-images.githubusercontent.com/2281138/191654007-2b097a4c-38db-444f-8917-2c236fda2caa.png">

That was fast! Thanks @liuxiao37k .

**Comment by guillaumevernieres** [comment]
@liuxiao37k the length scales are definitely not what we would have expected. Out of curiosity, what does the std. dev. looks like for Temp, Salt, ssh and your biogeochem fields?

**Comment by guillaumevernieres** [comment]
@liuxiao37k , as a ref. , in case I didn't share the link already, similar work from a while back: https://events.ecmwf.int/event/199/contributions/1947/attachments/1164/2144/OceanDA-WS_Menetrier.pdf

Done at 1 deg resolution.

**Comment by liuxiao37k** [comment]
@guillaumevernieres sure. here are the plots for `stddev` generated from the 11 lag pairs (12 forecasts, 11 pairs). I don't have 24 forecasts yet. I'll squeeze in additional 24 forecasts, initialized every 5 days, between 20190101-20190630, to make 36 forecasts, and compare each pair at day 5 and day 10. so we will have (36-1) degree of freedom. yes, I've seen your plots based off the 1deg configuration, and been using them as a reference.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/191842127-672bcb75-8143-4fe7-b7c5-7c83c08b5c53.png">

<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/191842160-5b5cee00-e18f-4fdf-aff1-2e327b5e8834.png">

<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/191842179-b4297028-6153-47a8-bfa2-6a0493e3769a.png">

<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/191842203-9740d9cd-6ea3-49d6-85ff-7247e935b459.png">

**Comment by liuxiao37k** [comment]
Pinging @ShastriPaturi here as he would like to follow updates on this task. @ShastriPaturi : Currently I am working on generating more forecasts in order to obtain more lagged perturbations. I'll rerun bump training and update results/figures once I have 36 members (35 degree of freedom) initialized every 5 days from 6-month analysis.

**Comment by liuxiao37k** [comment]
@guillaumevernieres I updated figures of length scales and variance of background errors [here](https://drive.google.com/drive/folders/1dpJmGBiBaGxJ0mNr8YKrGxUulFHfidDK?usp=sharing) based on perturbations calculated from 30 time-lagged forecasts.

More ensemble members don't seem to make the scales prettier.
I turned on variance filter (just 1 iteration), and it took 3-4 hours to compute for each variable using `--partition=bigmem` and `--ntask 64`. I tried playing with several variables (i.e. `resol` and `nl0r`, not sure even they were used at all) in `:bump` but they didn't fundamentally change the patterns much.

yaml used:
vi /work/noaa/marine/xliu/pr1/build/soca/test/testinput/parameters_bump_cov_new.yml

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I updated figures of length scales and variance of background errors [here](https://drive.google.com/drive/folders/1dpJmGBiBaGxJ0mNr8YKrGxUulFHfidDK?usp=sharing) based on perturbations calculated from 30 time-lagged forecasts.
> 
> More ensemble members don't seem to make the scales prettier. I turned on variance filter (just 1 iteration), and it took 3-4 hours to compute for each variable using `--partition=bigmem` and `--ntask 64`. I tried playing with several variables (i.e. `resol` and `nl0r`, not sure even they were used at all) in `:bump` but they didn't fundamentally change the patterns much.
> 
> yaml used: vi /work/noaa/marine/xliu/pr1/build/soca/test/testinput/parameters_bump_cov_new.yml

Thanks @liuxiao37k . I think it's time to make use of the "dirac" application and see what these covariances would look like. Happy to tagup if need be ... The carrot is that you would be able to see how a change in one of your bgc fields would impact the rest of the state. We may have to change a few things in soca (I/we need to check).

**Comment by guillaumevernieres** [comment]
Closing this issue @liuxiao37k . We'll revisit/refocus in the near future.

**Comment by guillaumevernieres** [comment]
@liuxiao37k , I'm creating a new issue for the generation of the perturbations.
