### ISSUE TITLE
Revive the ecbuild/cmake build system for CICE/Icepack

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#309]
# Description 
Update the currently broken `ecbuild` build system in the JCSDA-internal fork of CICE.

# Criteria for done
A branch with the bug fix allowing to build the CICE and Icepack library as well as the CICE stand alone executable.

**Comment by guillaumevernieres** [comment]
While we wait to be granted `maintainer` role for the JCSDA CICE fork, the [feature/ecbuild-new](https://github.com/JCSDA-internal/CICE/tree/feature/ecbuild-new) branch of https://github.com/JCSDA-internal/CICE does the following:
- Addition of a bundle CMakeLists.txt that includes Icepack
- builds the CICE and Icepack libs as well as the CICE stand alone exec

**Comment by kestonsmith-noaa** [comment]
OK will do.  Might need some clarification though- the existing version does create:
Singularity> ls lib/*so -ltrh
-rwxrwxr-x 1 keston keston 3.0M Jul 14 17:24 lib/libicepack.so
-rwxrwxr-x 1 keston keston 7.1M Jul 14 17:25 lib/libcice6.so
Is there something else your looking for?

**Comment by guillaumevernieres** [comment]
> OK will do. Might need some clarification though- the existing version does create: Singularity> ls lib/*so -ltrh -rwxrwxr-x 1 keston keston 3.0M Jul 14 17:24 lib/libicepack.so -rwxrwxr-x 1 keston keston 7.1M Jul 14 17:25 lib/libcice6.so Is there something else your looking for?

Nope, just closing the issue since it's mostly resolved, except for a pr that would update the feature/ecbuild branch ... not doing that until I can merge branches. Marking this ticket as solved.
