### ISSUE TITLE
Duplicate static files for soca

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#32]
- Remove ..../marineda/soca-staticUPD
- Make ..../marineda/soca-static readable by the group
- Update places.yml and replace soca-staticUPD by soca-static

**Comment by guillaumevernieres** [comment]
"closes #32"
Should have been at the end of your pr description... details.

**Comment by flampouris** [comment]
Not before merging! :)

**Comment by guillaumevernieres** [comment]
> Not before merging! :)

Not sure what you mean. Your pr addresses #32, if you want 32 to be closed after the merge ... which is what you usually would wand, you just add "closes #32". Not important, but it cleans up the issues.
