### ISSUE TITLE
3D FGAT for MOM6 in the gw

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#334]
## Description
Add the necessary steps in the g-w to cycle the `soca` 3dvar fgat implemented in the `GDASApp`.

## Dependencies
We're going to ignore the science for now and ignore the below dependencies.
- ~#332~ 
- ~#330~

## Criteria for done
- Ocean DA at least. Seaice, BGC, wave can be added later
- Marine DA tasks merged in the `global-workflow`

**Comment by guillaumevernieres** [comment]
Some progress:
![soca-in-g-w](https://user-images.githubusercontent.com/14031856/196811169-67f67271-90af-408e-b3f4-62d1801dc506.png)

It's currently only assimilating ADT, because that's all I have on Hera. It completed 1 cycle, including a coupled forecast with iau for mom6. :tada:

**Comment by ShastriPaturi** [comment]
👍🏻Sent from my iPhoneOn Oct 19, 2022, at 5:59 PM, Guillaume Vernieres ***@***.***> wrote:﻿
Some progress:

It's currently only assimilating ADT, because that's all I have on Hera. It completed 1 cycle, including a coupled forecast with iau for mom6. 🎉

**Comment by guillaumevernieres** [comment]
Done. Closing this issue and will write something more specific related to cycling.
