### ISSUE TITLE
Prototype Low-res weakly coupled DA system in the g-w/GDASApp

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#339]
## Description
It probably should have been its own epic ... but checking boxes is nice too:
- [x] **A:** 3dvar fgat with `soca` for the ocean only (sea-ice will come in later)
- [x] **B:** 3dvar fgat with the `gsi` for the atm (@RussTreadon-NOAA & @CoryMartin-NOAA )
- [x] **C:** trigger iau for MOM (G)
- [x] **D:** direct insertion of the `gsi` incr in the FV3 restart (@RussTreadon-NOAA and @CoryMartin-NOAA ) 
- [x] **E:** implement the `gdasfcst` step with the C48/5 deg MOM-CICE (mostly sorted out by @DeniseWorthen)
- [x] **F:** sort out task dependencies
~- [ ] **G:** Tidy code/submit PR's~

**Comment by guillaumevernieres** [comment]
@RussTreadon-NOAA , @CoryMartin-NOAA , a status update before tagging-up tomorrow: The forecast step segfault-ed for the `t18z` cycle (have not looked yet at why) but it ran fine for `t12z` (iau for MOM6, insertion of dummy incr for FV3).

![g-w](https://user-images.githubusercontent.com/14031856/198146419-4dedfd28-711e-47f7-b838-da51c553b6d1.png)

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres, I checked`/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/runs/s2s-test/testc48/COMROT/testc48/logs/2021032318/gdasfcst.log`.    According to this log file the 2021032318 gdasfcst successfully ran to completion.  Is this the correct log file to check?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres, I checked`/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/runs/s2s-test/testc48/COMROT/testc48/logs/2021032318/gdasfcst.log`. According to this log file the 2021032318 gdasfcst successfully ran to completion. Is this the correct log file to check?

Sorry @RussTreadon-NOAA , I meant to post an update last night and I forgot. Yes, the fcst ran to completion.

**Comment by RussTreadon-NOAA** [comment]
> > @guillaumevernieres, I checked`/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/runs/s2s-test/testc48/COMROT/testc48/logs/2021032318/gdasfcst.log`. According to this log file the 2021032318 gdasfcst successfully ran to completion. Is this the correct log file to check?
> 
> Sorry @RussTreadon-NOAA , I meant to post an update last night and I forgot. Yes, the fcst ran to completion.

Excellent!  Thanks, @guillaumevernieres , for the confirmation.

**Comment by guillaumevernieres** [comment]
While **A-F** works and sits in a few branches, it needs a major clean up before it can be submitted as a PR in the global-workflow. 
The part that lives in the GDASApp is relatively clean, the global-workflow changes needs some major TLC. Re-titles to prototype and closing this issue.
