### ISSUE TITLE
BGC obs

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#348]
## Description
Populate BGC R2D2 experimental data base.

# Criteria for done
- Enough BGC obs to test post 2019

**Comment by guillaumevernieres** [comment]
@liuxiao37k , is this issue sorted out?

**Comment by liuxiao37k** [comment]
@guillaumevernieres We have populated R2D2 with ocean color obs (2002-2022 May, thanks to @ShastriPaturi for transferring the files), but I am reprocessing everything this week to add an additional variable, and am also processing a new set of L4 data. I'd keep this open for a few more days until we replace the old files with new ones, if it's okay.

**Comment by ShastriPaturi** [comment]
> @guillaumevernieres We have populated R2D2 with ocean color obs (2002-2022 May, thanks to @ShastriPaturi for transferring the files), but I am reprocessing everything this week to add an additional variable, and am also processing a new set of L4 data. I'd keep this open for a few more days until we replace the old files with new ones, if it's okay.

Thanks @liuxiao37k . Let me know when you are ready.
