### ISSUE TITLE
Process SMOS ESA L2 SSS data for 2019

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/godas#353]
IODA-v2 convert SSS SMOS L2 obtained from ESA for the period 2019. The variables (SSS data, ObsError and QC flags are what are used by RTOFS-DA as well).

**Purpose**
1. To run OSE experiments
2. As a step towards GFSv17, since these data are also available on NCEP data tanks.

**Comment by ShastriPaturi** [comment]
SSS SMOS ESA L2 data are converted for 2019 and pushed to R2D2.
2020 data files are empty.

Thanks @mjhossen for doing this.

**Comment by guillaumevernieres** [comment]
Is this done @ShastriPaturi and @mjhossen ?

**Comment by ShastriPaturi** [comment]
> Is this done @ShastriPaturi and @mjhossen ?

@guillaumevernieres It is done for 2019. 2020 dataset is empty. Need to be downloaded again. Will mark it complete once I have done that.

**Comment by ShastriPaturi** [comment]
Done and closing.
