### ISSUE TITLE
Change group ownership of R2D2 DB to da

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#359]
Change the ownership of the R2D2 Orion DB,
```
/work2/noaa/ng-godas/r2d2/
```
from `ng-godas` to `da`.

**Comment by ShastriPaturi** [comment]
@guillaumevernieres the /work2/noaa/ng-godas/r2d2 is in ng-godas and the ownership has already been changed to da.
(base) Orion-login-1[218] spaturi$ ls -ltrh ng-godas/
total 20K
drwxr-sr-x 3 spaturi da       4.0K May  5 14:20 r2d2

**Comment by guillaumevernieres** [comment]
arg ... must have been looking at the wrong fs. Thanks for checking @ShastriPaturi .
