### ISSUE TITLE
Change group ownership from `ng-godas` to `da`

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#360]
Pinging @kestonsmith-noaa since there might be other permission issues.

Group ownership of  `/work/noaa/ng-godas/marineda/DATM_INPUT/` needs to be changed recursively from `ng-godas` to `da`.

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, I do not have permission. The owners are:
ycteng and hlee

drwsrwsr-x  8 ycteng  ng-godas 16K Apr  4 13:37 DATM_INPUT

ls -ltrh DATM_INPUT

drwxrwsr-x  86 ycteng ng-godas 428K Mar 19  2021 org
drwxrwsr-x   4 ycteng da        16K Oct 30  2021 corr_factor
drwxrwsr-x 242 ycteng da        16K Jan 10  2022 GEFS
drwxr-s---  22 hlee   ng-godas 4.0K Apr  7 09:54 GEFS_new
drwxr-s---  16 hlee   ng-godas 4.0K May  4 13:42 GFS
drwxrwsr-x  70 ycteng da        16K May 27 18:48 CFSR

**Comment by guillaumevernieres** [comment]
@awest-noaa , could you take care of this? The files belong to @clouden90 (YC), we would need the ownership to be transferred to @ShastriPaturi .

**Comment by hyunchul386** [comment]
JFY, I tried to change the group of DATA_INPUT to da, but the operation not
permitted for me.

**Comment by guillaumevernieres** [comment]
@kestonsmith-noaa will be added to `ng-godas` ... somehow.
