### ISSUE TITLE
Missing ascending or descending orbits for SMOS, AMSR2 and GMI

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#372]
After applying obs_error filter (higher than .5), the followings (MW) obs are used in the assimilation. Not shown which are rejected by filter
![Screen Shot 2022-08-29 at 2 03 59 PM](https://user-images.githubusercontent.com/65732322/187268725-ca2b3f32-9ac7-48f4-8e11-ab4911571a14.png)

_Originally posted by @mjhossen in https://github.com/NOAA-EMC/godas/issues/298#issuecomment-1230676206_

**Comment by guillaumevernieres** [comment]
Something to remember to look into @ShastriPaturi . Not high priority.

**Comment by ShastriPaturi** [comment]
AMSR-2, Raw and in r2d2 (the day and night passes are present) Issue with date?
![image](https://user-images.githubusercontent.com/26145004/189731315-a748b88b-6ced-414c-8833-4892fa8d45c5.png)
![image](https://user-images.githubusercontent.com/26145004/189731370-69286ebb-df65-4d54-963d-81a525546a5b.png)

**Comment by ShastriPaturi** [comment]
SSS SMOS L2 ESA, raw & R2D2 (ascending & descending passes download fixed)
![image](https://user-images.githubusercontent.com/26145004/189735024-643630bf-af0c-490e-9055-36a010a8cf92.png)
![image](https://user-images.githubusercontent.com/26145004/189735094-2f896968-ffdc-4bf3-b798-dba244603e45.png)

**Comment by ShastriPaturi** [comment]
GMI, Raw and in r2d2 (the day and night passes are present) Issue with date?
![image](https://user-images.githubusercontent.com/26145004/189737766-0081af82-66ea-4c02-836c-8c7ab9b3034b.png)
![image](https://user-images.githubusercontent.com/26145004/189737849-c7572c81-6630-4021-bdd3-55411dffc52f.png)

**Comment by mjhossen** [comment]
Update SMOS data shows both ascending and descending swath. Here is a plot of Obserror for sss_smos: 
![Screen Shot 2022-09-12 at 3 48 58 PM](https://user-images.githubusercontent.com/65732322/189742997-70ace05a-bb10-4345-b5f9-ae70baf9eedc.png)

**Comment by mjhossen** [comment]
However, GMI and AMSR2 (ObsError) shows something different from what @ShastriPaturi shows. I use the database as
```
R2D2_DB_DIR=/work2/noaa/ng-godas/r2d2/
R2D2_PROVIDER="gdas_marine"
R2D2_EXP="s2s_v1"
```
@ShastriPaturi what do you mean by issue with date?
![Screen Shot 2022-09-12 at 3 58 45 PM](https://user-images.githubusercontent.com/65732322/189747916-80e7bad2-fc2c-4110-a078-bc9f6b8feece.png)
![Screen Shot 2022-09-12 at 4 00 03 PM](https://user-images.githubusercontent.com/65732322/189747928-bb8f0c80-1bab-41bc-a8d4-27c1fe1bbd39.png)

**Comment by ShastriPaturi** [comment]
@mjhossen are you plotting these from obs_out?

**Comment by mjhossen** [comment]
Yes, from obs_out in EXP1 without any filter.

**Comment by ShastriPaturi** [comment]
Can you plot the AMSR-2 and GMI from R2D2 as a second check?

**Comment by mjhossen** [comment]
Yes. I will.

**Comment by mjhossen** [comment]
I copied the file from /work2/noaa/ng-godas/r2d2/gdas_marine/ob/s2s_v1/P1D/2019-01-01/gdas_marine.s2s_v1.ob.P1D and got the same figure as @ShastriPaturi 
![Screen Shot 2022-09-12 at 4 54 16 PM](https://user-images.githubusercontent.com/65732322/189757962-bdbf58ca-702a-4501-b12b-b98487b6b143.png)
But in obs_out I found the following: 
![Screen Shot 2022-09-12 at 4 56 57 PM](https://user-images.githubusercontent.com/65732322/189758295-c3f73c21-8c55-4523-a6b4-c075d621f2c6.png)
Here is the folder for sst_gmi..yaml: /work/noaa/marine/jhossen/marine_DA_dev/OSE_final/expt1_gmi_test
![Screen Shot 2022-09-12 at 5 07 26 PM](https://user-images.githubusercontent.com/65732322/189758998-729ca922-2eae-4783-8e3e-5f2dfd5f3778.png)

**Comment by mjhossen** [comment]
I think the problem is Z12 in start date we use in exp_config. We should have start our exps with start date as 20190101Z00.  I do not know whether it could be a problem for SSS or other data.

**Comment by guillaumevernieres** [comment]
> I think the problem is Z12 in start date we use in exp_config. We should have start our exps with start date as 20190101Z00. I do not know whether it could be a problem for SSS or other data.

@mjhossen , No, you should be able to start your experiment whenever. If there is a bug it is:
1 - the obs date is shifted in the file by 12 hours (12 hours of the previous day + 12 hours of the current day)
2 - something is wrong in the processing, but I doubt it since it's been working with other obs type so far, so check 1 above ... ncdump of the date of the file will tell you if 1 is the issue.

**Comment by mjhossen** [comment]
> 

I got your point.

**Comment by mjhossen** [comment]
Here is a snapshot: 
![Screen Shot 2022-09-12 at 5 33 25 PM](https://user-images.githubusercontent.com/65732322/189762641-2d0c693e-9551-4282-852d-91b5917f490b.png)
In the data file, I see the date is around 12 hours (+- 12)

**Comment by ShastriPaturi** [comment]
@mjhossen can plot a time-series of the datetime?
