### ISSUE TITLE
Diagnostic tools: EVA for BGC

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#375]
# Description
Start making use of EVA for analyzing biogeochemistry in observation and state space.

**Current location:** [https://github.com/danholdaway/eva/](https://github.com/danholdaway/eva/)

**Documentation:** https://danholdaway.github.io/eva/#/

**HPC modules:** EVA/orion or EVA/hera

# Definition of done
Basic use of EVA with `SNPP`, `AQUA`, 'NOAA20`, `DINEOF3` ioda output example to plot:
- histograms
- maps
- scatter plots

Tutorial on how to reproduce plots above to be written in markdown format in this issue.

@liuxiao37k , feel free to update the issue as you see fit.

**Comment by liuxiao37k** [comment]
@mjhossen thanks for helping to test existing evaluation tools for BGC. Some `obs_out` files you could use:
old runs on Orion (only one OC product was used, snpp): 
```
/work/noaa/ng-godas/xliu/sandbox/27oct21/test_run_bgc2/obs_out/
```
ongoing runs on Gaea (four OC obs products were used, snpp, aqua, noaa20, dineof3): 
```
/lustre/f2/dev/ncep/Xiao.Liu/sandbox/27jun2022/PSL_scout_BGC/obs_out/
```

**Comment by guillaumevernieres** [comment]
I'm closing this issue and will create a new one more specifically targeted to adding a feature to `eva`.

**Comment by mjhossen** [comment]
To use EVA:
```
- module use GDASApp/modulefiles
- module load EVA/orion
- eva name_of_yaml
```
