### ISSUE TITLE
Establish a new reference analysis

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#379]
# Description
Similar to what was done for the EMC studies and PSL, establish a new reference analysis (time period TBD) using the latest version of `soca` and the `UFS` (p8 and ~~cice6 c-grid~~).

## UFS:
- new config (ask @ShastriPaturi)
- **DO NOT** ~~trigger c-grid for CICE6~~ (ask @ShastriPaturi)
   - https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/parm/ice_in_template#L51
   - https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/tests/cpld_control_ciceC_p8#L83 
- IC from PSL

## OBS:
- check obs processing status with @ShastriPaturi
- check with @mjhossen if we should assimilate MW

## DA notes:
- soca-science: something recent from `stable-nightly`
- make use of 3D BUMP, check with @liuxiao37k 
- seaice DA with old cice init should be on

## Time period:
**After discussion with @travissluka , we decided to change the start date to 2021-07-01**
this will allow us to compare our analysis to the JCSDA golden month.

Start from `EMC2`: ```/work/noaa/marine/jhossen/EMC2/rst/2021070100```

# Deliverable
- Documentation of the experiment
- ufs config for p8 ~~and cice6 c-grid~~
- ...

**Comment by ShastriPaturi** [comment]
1. Provided the ufs_config on orion. 
2. The insitu FNMOC profiles with PreQC filter has been added to R2D2 (/work2/noaa/ng-godas/r2d2). Please check for few cycles (1 week) from 20190101.

**Comment by guillaumevernieres** [comment]
@hyunchul386 : The CICE consortium is advising against the use of the c-grid for CICE (thanks for the head's up @JessicaMeixner-NOAA) ... So lets revert back.

**Comment by hyunchul386** [comment]
Okay, the reference run will be CICE-B.

**Comment by guillaumevernieres** [comment]
@hyunchul386 , please note that the start date changed to **2021-07-01-00**

**Comment by guillaumevernieres** [comment]
@hyunchul386 , could you give us an update on the status of this experiment?

**Comment by hyunchul386** [comment]
I will update it in the meeting

**Comment by hyunchul386** [comment]
The working directory of the new reference run is
/work/noaa/marine/Hyun-Chul.Lee/emc_ref

**Comment by guillaumevernieres** [comment]
@hyunchul386 closing this, assuming this is done.
