### ISSUE TITLE
Run a canned 1/4 c384 S2S forecast

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#382]
# Description
- clone/build the global-workflow
- setup an experiment
- document the steps from build to running a test case

See documentation: https://github.com/NOAA-EMC/global-workflow/wiki/Run-Global-Workflow

**Comment by JessicaMeixner-NOAA** [comment]
If you want to use already staged canned -ICs for S2S, use IC date of 2013010100 (there are others too)

**Comment by guillaumevernieres** [comment]
Tested here:
```
expdir: /work/noaa/da/aeichman/para/astral
comrot: /work/noaa/stmp/aeichman/comrot/astral
```
Thanks @AndrewEichmann-NOAA
