### ISSUE TITLE
Add L4 daily sea-ice concentration to R2D2

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#386]

**Comment by ShastriPaturi** [comment]
20190101: ICEC from NSIDC L4

![image](https://user-images.githubusercontent.com/26145004/191124945-d32ecbd9-fccd-4721-90ee-783fae7f4a5f.png)

I will push to R2D2

**Comment by guillaumevernieres** [comment]
> 20190101: ICEC from NSIDC L4
> 
> ![image](https://user-images.githubusercontent.com/26145004/191124945-d32ecbd9-fccd-4721-90ee-783fae7f4a5f.png)
> 
> I will push to R2D2

Thanks @ShastriPaturi ... that would be very helpful!

**Comment by guillaumevernieres** [comment]
@ShastriPaturi : Is the converter correct in the arctic? it seems that obs are missing ... Also, where are the 0 values? Are these the obs that you are using @jieshunzhu ?

**Comment by ShastriPaturi** [comment]
I did a quick conversion and plot. I will double check with Jieshun tomorrow and get the converter from him.

**Comment by ShastriPaturi** [comment]
![image](https://user-images.githubusercontent.com/26145004/191259158-4ca201c6-687d-45f7-a322-634cf3694d9f.png)
Looks fine.
But will compare this against the one from @jieshunzhu as well.

**Comment by jieshunzhu** [comment]
Very occasionally, either ice fraction or obs error in original NSIDC data
is 0. In that case, there will be no records in converted data.

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, the difference between the two plots is that plot 1 has obs removed when the error is 0, the second one does not. I will plot for few other days. Definitely we need the IODA files with error != 0.

**Comment by ShastriPaturi** [comment]
All obs
![image](https://user-images.githubusercontent.com/26145004/191341571-e29208ad-43d6-43c7-88b0-80d36895e8ba.png)
With err=0 removed
![image](https://user-images.githubusercontent.com/26145004/191342303-3d6f10ac-f135-45fd-9de4-336c27c7c6bc.png)

**Comment by ShastriPaturi** [comment]
![image](https://user-images.githubusercontent.com/26145004/191347512-bfb65b8c-ee45-4a88-9f0d-baf909327791.png)
![image](https://user-images.githubusercontent.com/26145004/191347796-bdcddbd2-6f86-47da-af95-e0d661c2bafe.png)

**Comment by guillaumevernieres** [comment]
@ShastriPaturi , @jieshunzhu , you need to keep the obs where the estimated error is 0 ... It makes sense too, 0 errors seems to be where the ice concentration is most likely 0 or 1. Add a small offset to the processing of the error, or a filter to the ufo. I vote for adding a small offset to the original obs error.

**Comment by ShastriPaturi** [comment]
I added a 0.01 offset where the error is 0.
![image](https://user-images.githubusercontent.com/26145004/191362319-129a4f01-35b8-4cac-b9bf-8f23e4e60613.png)

**Comment by ShastriPaturi** [comment]
0.01 has conflicts. Will use 0.0001

**Comment by ShastriPaturi** [comment]
Pushed to R2D2 3 months of data from 2019-01-01 till 2019-03-31.
Will complete till rea-time.
Closing this issue as complete.

**Comment by guillaumevernieres** [comment]
@ShastriPaturi , time is set to "undef" ... Set it to 0.

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, time is variable added by the ioda-upgrade.x, since the converter uses the old format. Will update the converter to IODA-v2.
Closing this issue.
