### ISSUE TITLE
Add L4 sea-ice concentration to R2D2

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#387]

**Comment by guillaumevernieres** [comment]
@ShastriPaturi , note for Monday: Usable to plot and compare but cannot be processed in the preqc step in soca-sci ... Needs investigation.

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, I have updated the nsidc L4 converter, converted and pushed to R2D2 for 20190101. I need to test it on my side as well.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres, I have updated the nsidc L4 converter, converted and pushed to R2D2 for 20190101. I need to test it on my side as well.

looks like we're posting on the wrong issue ... this is supposed to be about ice thickness, I suppose you are referring to ice concentration?

**Comment by ShastriPaturi** [comment]
The IODA converter has been updated.
The NSIDC CDR L4 for 2019 is converted and pushed to r2d2.
A PR is underway.
