### ISSUE TITLE
Process L2 sea-ice concentration from AMSR-2 (available in NCEP Data tanks)

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/godas#389]
```
The sea-ice concentration from AMSR-2 coming into the NCEP data tanks spans from 2020-10-05 till real-time.
1. Search for obs prior to 2020-10-05.
2. Create a new IODA converter and push to R2D2.

**Comment by ShastriPaturi** [comment]
IODA converter is ready. The converted file for 20210801 needs to be tested.

**Comment by ShastriPaturi** [comment]
Raw obs: 20210801
![image](https://user-images.githubusercontent.com/26145004/193923729-5d530518-aefa-4d4c-8137-797749f38264.png)

**Comment by guillaumevernieres** [comment]
That's 24hrs of obs @ShastriPaturi ?

**Comment by ShastriPaturi** [comment]
Yes @guillaumevernieres

**Comment by ShastriPaturi** [comment]
IODA-v2: 20210801
![image](https://user-images.githubusercontent.com/26145004/194165666-36df229f-4312-45ac-a6fb-192a067ca6c7.png)
No QC filter is applied. There is no error estimate provided, applied 0.1.

**Comment by ShastriPaturi** [comment]
> IODA-v2: 20210801 ![image](https://user-images.githubusercontent.com/26145004/194165666-36df229f-4312-45ac-a6fb-192a067ca6c7.png)

I did not apply any qc filter

**Comment by guillaumevernieres** [comment]
@ShastriPaturi , please close if this is done.
