### ISSUE TITLE
Process L3U SST from Geostationary satellites (GOES-<16,17>) and HIMAWARI-08 (NCEP Data Tanks)

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/godas#390]
```
The L3U SST from Geostationary satellites (GOES-<16,17>) and HIMAWARI-08 available in NCEP data tanks span from 2020621 (GOES-16) till real_time.

1. Search for previous years.
2. Create a IODA converter 
3. Super-ob to 0.25 deg
4. Push to R2D2.
```

**Comment by ShastriPaturi** [comment]
@mjhossen, the data are on hera. Please start with 20210801.
/scratch2/NCEPDEV/marine/Shastri.Paturi/DATA_realtime/20210801/sst 

Example files (Data are hourly):
GOES-<16,17> (ABI is the sensor - Advanced Baseline Imager)
20210801230000-STAR-L3C_GHRSST-SSTsubskin-ABI_G16-ACSPO_V2.70-v02.0-fv01.0.nc
20210801230000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
Himawari-08 (AHI is the sensor - Advance Himawari Imager)
20210801230000-STAR-L3C_GHRSST-SSTsubskin-AHI_H08-ACSPO_V2.70-v02.0-fv01.0.nc

**Comment by mjhossen** [comment]
@ShastriPaturi  Which script we can use?

**Comment by ShastriPaturi** [comment]
@mjhossen you can use gds2_sst2ioda.py .Sent from my iPhoneOn Oct 5, 2022, at 5:15 PM, mjhossen ***@***.***> wrote:﻿
@ShastriPaturi  Which script we can use?

**Comment by mjhossen** [comment]
Converted a 10 min file (see a figure). Should we push sst_goes to PT10M database? Before pushing to r2d2 database, should we do superobing?
![Screen Shot 2022-10-11 at 3 38 48 PM](https://user-images.githubusercontent.com/65732322/195184497-ce31d1eb-e032-4a57-83c6-de143bbb6a1f.png)

Is it 10-min or hourly?

**Comment by guillaumevernieres** [comment]
Yes @mjhossen , all the sst obs have to be superobed, that's what we discussed this am. We're not keeping the raw or not superobed files.

**Comment by ShastriPaturi** [comment]
@mjhossen Thanks for the plot.
Please plot for all the swaths.

Please super-ob to 0.25 deg grid. Ping me when you complete converting for 20210801.
I will provide info on superobbing.

**Comment by mjhossen** [comment]
Completed. Files are located at  /work2/noaa/ng-godas/jhossen/sst_goes/20210801/

**Comment by ShastriPaturi** [comment]
@mjhossen you only needed to convert GOES (ABH) and Himawari (AHI).
Also, you need to convert the hourly files to daily files and super-ob them.

**Comment by mjhossen** [comment]
@ShastriPaturi I think it is better to superob the hourly data first and then concatenate them for daily. I submitted a job for producing a daily file but stopped without completing because to time limit (8 hrs).

**Comment by guillaumevernieres** [comment]
> @ShastriPaturi I think it is better to superob the hourly data first and then concatenate them for daily. I submitted a job for producing a daily file but stopped without completing because to time limit (8 hrs).

@mjhossen  , things got lost in translations ... Yes, superob the hourly file and then concatenate. Sorry this wasn't communicated properly, but this is what we've had to do for all the sst retreivals.

**Comment by ShastriPaturi** [comment]
@mjhossen, copy the following files from 
/work/noaa/ng-godas/spaturi/nggodas_realtime_ext/DATA_realtime/cron/ioda-v2/sst_10min

1. create_obs2ioda.sh (submits batch job to ioda-convert, for you the hourly files)

- godas_obs2ioda.sh

2. godas_superob.sbatch (submits superobing batch job, you may have to update directories related to soca-science

- godas_store_obs.py & godas_obs2ioda.utils
Let me know if you have issues.

**Comment by mjhossen** [comment]
@ShastriPaturi Some hours data are missing for G17:
20210811/sst/20210811000000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
20210811/sst/20210811010000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
20210811/sst/20210811020000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
20210811/sst/20210811030000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
20210811/sst/20210811040000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
20210811/sst/20210811050000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
20210811/sst/20210811060000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
20210811/sst/20210811070000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
20210811/sst/20210811080000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
20210811/sst/20210811200000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
20210811/sst/20210811210000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
20210811/sst/20210811220000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc
20210811/sst/20210811230000-STAR-L3C_GHRSST-SSTsubskin-ABI_G17-ACSPO_V2.71-v02.0-fv01.0.nc

**Comment by ShastriPaturi** [comment]
@mjhossen continue with what is there. I will get files from HPSS and fill in the missing files if they are available

**Comment by mjhossen** [comment]
Ioda-conversion and superobing of SST GOES<G16,G17> & Himawari H08 is completed for the period of 20210801-20210831. Superobs data is located at /work2/noaa/ng-godas/jhossen/sst_goes/superob

**Comment by ShastriPaturi** [comment]
Thanks @mjhossen.
Please do the the plots too.

**Comment by mjhossen** [comment]
Plot ObsValue for 20210801 (24 hours) ABI_<G16, G17> and AHI_H08 superobs data:
![Screen Shot 2022-10-19 at 5 36 35 PM](https://user-images.githubusercontent.com/65732322/196809575-0570728f-660a-4337-8c7e-24d21a8f9f30.png)
![Screen Shot 2022-10-20 at 11 34 06 AM](https://user-images.githubusercontent.com/65732322/196993968-6f4d760a-9352-47dd-aec5-4aa52205a4af.png)
![Screen Shot 2022-10-20 at 11 34 23 AM](https://user-images.githubusercontent.com/65732322/196993972-4daf831e-7663-444e-a8b0-25565ad07912.png)

**Comment by mjhossen** [comment]
ObsError (superobs):
![Screen Shot 2022-10-20 at 11 50 18 AM](https://user-images.githubusercontent.com/65732322/196997433-622f1593-1a66-48ef-8dc5-1a02418a6764.png)
![Screen Shot 2022-10-20 at 11 50 41 AM](https://user-images.githubusercontent.com/65732322/196997440-60323169-bddc-475f-aa3f-5b5f15bd9366.png)
![Screen Shot 2022-10-20 at 11 53 55 AM](https://user-images.githubusercontent.com/65732322/196998165-1b54e4fc-8e04-4cb1-ba1e-b7316975dc9c.png)

**Comment by guillaumevernieres** [comment]
@ShastriPaturi @mjhossen , is this done?

**Comment by ShastriPaturi** [comment]
Yes. Closing this issue
