### ISSUE TITLE
EnVAR with static perturbations

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#393]
# Description
Follow #379 's setup and start date (... if possible, to be discussed with @liuxiao37k).
Use the fcst lag differences prepared by @liuxiao37k as a static ensemble for a hybrid envar.

The use of static perturbations will be a testbed for:
  - profile in more detail the envar
  - quantify the quality of the static ensemble ... We're currently unsure of the drift influence on the perturbations
  - test current updates (this might require some changes in the function that prepares the mom6 iau incr ...)
  - ...
  
# Tech. details
Use the `3dvar` option of soca-science, but re-write the `var.yaml` to include a hybrid background error:
- parametric, same as what we have now
- ens: pointing to @liuxiao37k static ensemble
@liuxiao37k , let me know when you are ready to work on this, I can help you out write the `3dvar.yaml`.

**Comment by liuxiao37k** [comment]
Notes from tagup:
1. create a yaml based off 3dvar yaml by placing the covariance model config portion with ensemble based keys and inputs, pointing to the static perturbation files. 
2. use 3dvar option in soca-science.
3. additional steps in the 3dvar workflow to trigger localization and link static perturbation files to data dir.
4. make sure read in the required `h` as as a state, not as a perturbation.
5. if memory limitation occurs, attempt to reduce variables to at least produce the first round of results. I'll keep chlorophyll for sure!

@guillaumevernieres did I miss anything?

**Comment by guillaumevernieres** [comment]
Looks good @liuxiao37k

**Comment by liuxiao37k** [comment]
@guillaumevernieres: Summary for last Friday's discussion:
- first look at the EnVAR results:
1. with only ocean physical control variables (T, S, ssh, ice stuff): it (e.g. SST) looks okay but a bit worse than 3DBUMP and 2DBUMP+Vertconv;
2. with BGC variables added: terrible for chl, and it makes SST terrible too. "refinement" is needed.
- next round:
1. tune parameters used in localization, especially in the vertical;
2. actually initialize an ensemble (also 30 members? maybe 40?) of forecasts on the first day of the month and run them for 15-30 days and use that as the static ensemble in EnVAR for the month? be careful when saving output - perhaps saving restarts every 5-10 days.
- Something else to take a look:
add u and v to the control variables - need to remove the `strap` set in soca, and make sure to not assimilate obs.

**Comment by guillaumevernieres** [comment]
@liuxiao37k , Same here, closing this issue. We'll re-write/re-focus the EnVAR work.
