### ISSUE TITLE
Add L4 sea-ice thickness to R2D2

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#394]
- Download L4 sea ice thickness from Copernicus for the period of 2019-present ... TBD, size dependent
- Create a ioda converter
- Convert, check obs and push to R2D2

**Comment by ShastriPaturi** [comment]
@guillaumevernieres does this include the ice freeboard?

**Comment by mjhossen** [comment]
Can you please put the link from where I can download the data?

**Comment by guillaumevernieres** [comment]
> Can you please put the link from where I can download the data?

You'll have to navigate the Copernicus page @mjhossen. I do remember seeing a L4 ice thickness product but not 100% sure.

**Comment by ShastriPaturi** [comment]
@mjhossen Copernicus page does have the ice thickness. 
https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-sea-ice-thickness?tab=form

**Comment by mjhossen** [comment]
Downloaded data from CryoSat-2 for 2019-present. CDR covers Oct 2002 - Apr 2020 for version 2.0 and ICDR from Oct 2020 to present for version 2.0

**Comment by mjhossen** [comment]
I am able to convert sea-ice thickness into ioda format. Upper panel shows converted data and lower shows raw data.
![Screen Shot 2022-10-07 at 10 38 00 AM](https://user-images.githubusercontent.com/65732322/194581743-1522d174-675c-4694-99fa-e14a93554c3d.png)
![Screen Shot 2022-10-07 at 10 40 30 AM](https://user-images.githubusercontent.com/65732322/194581748-1fa5c61e-6a9f-47ad-8e92-4bf97a08f314.png)

**Comment by guillaumevernieres** [comment]
Thanks @mjhossen . Are these daily averages?

**Comment by mjhossen** [comment]
They are monthly average. The time coverage is 20190101 to 20190131

**Comment by mjhossen** [comment]
Completed for 2019 and 2020 as only data is available. Data is located at /work2/noaa/ng-godas/jhossen/icethk_coperl4

**Comment by ShastriPaturi** [comment]
Thanks @mjhossen.
A quick question: what is the date in your IODA converted file?
@guillaumevernieres and @mjhossen, since these are monthly averages, I think these data need to be a new directory on r2d2 /work2/noaa/ng-godas/r2d2/*/P1M instead of P1D.

**Comment by ShastriPaturi** [comment]
@mjhossen there are ioda converted files missing between 201905-201909

**Comment by guillaumevernieres** [comment]
> Thanks @mjhossen. A quick question: what is the date in your IODA converted file? @guillaumevernieres and @mjhossen, since these are monthly averages, I think these data need to be a new directory on r2d2 /work2/noaa/ng-godas/r2d2/*/P1M instead of P1D.

@mjhossen , @ShastriPaturi I would suggest to pick a date in the middle of the month and store it in P1D. 

In the past, I simply interpolated the obs down to daily fields, good enough as a diagnostic observation and we won't implement a time average operator anytime soon!

**Comment by guillaumevernieres** [comment]
> @mjhossen there are ioda converted files missing between 201905-201909.

That's correct @ShastriPaturi  there are no retrievals of ice free board/thickness during that period of the year.

**Comment by ShastriPaturi** [comment]
@mjhossen is it doable for you to interpolate the obs to daily fields as @guillaumevernieres mentioned?

**Comment by mjhossen** [comment]
> @mjhossen there are ioda converted files missing between 201905-201909

Data is not available!

**Comment by mjhossen** [comment]
> @mjhossen is it doable for you to interpolate the obs to daily fields as @guillaumevernieres mentioned?

It would be same for each day for the coverage month.

**Comment by mjhossen** [comment]
Do you want me to create each day file by taking the same monthly data cover the month?

**Comment by guillaumevernieres** [comment]
> Do you want me to create each day file by taking the same monthly data cover the month?

Forget about interpolated for now @mjhossen , just monthly files with the date set to the middle of the month is fine.

**Comment by mjhossen** [comment]
Done with the date set to 15th of every month!

**Comment by mjhossen** [comment]
Plots by EVA
![Screen Shot 2022-10-12 at 11 19 14 AM](https://user-images.githubusercontent.com/65732322/195382789-84efd9e0-0506-4bff-9bae-d78e5080b242.png)
![Screen Shot 2022-10-12 at 11 19 32 AM](https://user-images.githubusercontent.com/65732322/195382792-7d8c280d-25e5-4f0b-bf16-3ee53c7a4cae.png)

**Comment by guillaumevernieres** [comment]
clearly not the polar stereo graphic projection that we want @mjhossen .

**Comment by mjhossen** [comment]
I agree. I will talk to Cory tomorrow.

**Comment by guillaumevernieres** [comment]
> I agree. I will talk to Cory tomorrow.

@mjhossen  Can you look into the code, you just need to pass a few more arguments to the projection.

**Comment by mjhossen** [comment]
Done. After some modification, I plotted a figure the way we want. 
![Screen Shot 2022-10-13 at 9 20 14 AM](https://user-images.githubusercontent.com/65732322/195608133-ef8df6a8-262c-4bd9-b506-a83e69c1335b.png)

**Comment by guillaumevernieres** [comment]
@mjhossen  Nice! can you change the latitude lower bound to something similar to the plot at the top of the discussion? ... and then do the same thing for the south polar stereo :)

**Comment by ShastriPaturi** [comment]
> Done. After some modification, I plotted a figure the way we want. 
![Screen Shot 2022-10-13 at 9 20 14 AM](https://user-images.githubusercontent.com/65732322/195607954-2d2347fb-efad-49dd-bc4d-9fd0a932aaf3.png)

Nice work @mjhossen

**Comment by mjhossen** [comment]
EVA plot (latest)
 
![Screen Shot 2022-10-13 at 10 20 53 AM](https://user-images.githubusercontent.com/65732322/195622964-aabf38a6-5ff5-4091-b8b3-36d568d7de0c.png)

**Comment by ShastriPaturi** [comment]
@mjhossen can you share path of the IODA-v2 converted obs here?

**Comment by mjhossen** [comment]
Here is the dir: /work2/noaa/ng-godas/jhossen/icethk_coperl4

**Comment by ShastriPaturi** [comment]
The data has been moved to R2D2.
@mjhossen have you created a PR for the converter?
