### ISSUE TITLE
L4 ADT from Copernicus

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#398]
Check if we can get ADT from 2019-present. If so, download, convert and push to r2d2.

**Comment by mjhossen** [comment]
@ShastriPaturi Can you please put the ftp link for downloading the copernicus level 4 data?

**Comment by mjhossen** [comment]
I downloaded the data from the link:
```
https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-sea-level-global?tab=form
```

**Comment by mjhossen** [comment]
Data is available until 2022-02-09. Conversion is completed. Data is located in the Orion at /work2/noaa/ng-godas/jhossen/adt_coperl4

**Comment by ShastriPaturi** [comment]
Thank you @mjhossen.
Spatial plots of ObsError, ObsValue between raw and IODA-v2 converted data for a day or two will helpful.
Also, having a download script will be helpful.

**Comment by mjhossen** [comment]
![Screen Shot 2022-10-03 at 5 27 25 PM](https://user-images.githubusercontent.com/65732322/193686542-117098c6-e765-4667-afff-95d8bff93227.png)

**Comment by mjhossen** [comment]
Raw data plotted by ncview: 
![Screen Shot 2022-10-03 at 5 37 44 PM](https://user-images.githubusercontent.com/65732322/193689844-9707475b-ef9e-427b-9fa8-d95a6b12e826.png)

**Comment by ShastriPaturi** [comment]
Pushed to r2d2. Thanks @mjhossen.
@guillaumevernieres should this issue be kept open? The latency of the updates are 6 months.

**Comment by guillaumevernieres** [comment]
> Pushed to r2d2. Thanks @mjhossen. @guillaumevernieres should this issue be kept open? The latency of the updates are 6 months.

Nope, closing right now @ShastriPaturi . We'll revisit in the future if need be. Thanks for doing this @mjhossen.
