### ISSUE TITLE
L2 CryoSat-2 ice freeboard data from NESDIS

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/godas#401]
L2 CryoSat-2 ice freeboard data from NESDIS is available from October 2018 - March 2019.

1. Create a script to download from:
    ftp://ftp.star.nesdis.noaa.gov/pub/socd/lsa/aegido/ffsar_Arctic_2018_2019/L2_80Hz
2. Update existing ice freeboard IODA-converter and convert to IODA-v2 format
    https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/marine/cryosat_ice2ioda.py 
3. The QC flags are provided as surfaceType. It does not contain any information on obs error. For the moment, use 0.01 m.

**Comment by mjhossen** [comment]
There is something wrong in the data file. I am converting 2018-10-02 data file
The reference time is given 1985-01-01
        double time(time) ;
                time:long_name = "UTC time [s]" ;
                time:units = "seconds since 1985-01-01 00:00:00" ;
and the time is given in the second. 
After converting into date format, we got 2048 though the data file's date is 2018:
datetime = "2048-10-01T23:34:40Z", "2048-10-01T23:34:40Z",
      "2048-10-01T23:34:40Z", "2048-10-01T23:34:40Z", "2048-10-01T23:34:40Z",
      "2048-10-01T23:34:40Z", "2048-10-01T23:34:40Z", "2048-10-01T23:34:40Z",

**Comment by mjhossen** [comment]
I need to put a reftime as 1955-01-02 23:59:24 that provides consistent time and date.

**Comment by ShastriPaturi** [comment]
Thanks @mjhossen .
We will have to contact the provider.

Could you generate spatial plots of ObsValue : raw and convertered?

**Comment by ShastriPaturi** [comment]
@mjhossen can share the path to your IODA converted data?

**Comment by mjhossen** [comment]
The folder is located at /work2/noaa/ng-godas/jhossen/icefb_cryosat2

**Comment by mjhossen** [comment]
It seems something wrong. What do you think?
![Screen Shot 2022-10-21 at 4 32 32 PM](https://user-images.githubusercontent.com/65732322/197285297-cd1e548f-6500-4a9f-a237-3013095ea4ea.png)

**Comment by guillaumevernieres** [comment]
your color scale is off @mjhossen , try [0, 0.3].

**Comment by mjhossen** [comment]
Updated as suggested
![Screen Shot 2022-10-27 at 11 41 01 AM](https://user-images.githubusercontent.com/65732322/198336550-549488aa-e012-42be-a9c5-93c797dbeffd.png)

**Comment by ShastriPaturi** [comment]
@mjhossen can you complete the conversion for Oct 2018 - March 2019 data?
Also, can you rename the files as: icefb_c2_nesdis_YYYYMMDD.nc?

**Comment by ShastriPaturi** [comment]
Please save your files as YYYY/YYYYMMDD/icefb_c2_nesdis_YYYYMMDD.nc.
It is how the directory structure should be for pushing to R2D2. Thanks

**Comment by mjhossen** [comment]
Done for the period of Jan 01 2019 to Jan 31 2019

**Comment by ShastriPaturi** [comment]
No data during:
/work2/noaa/ng-godas/jhossen/icefb_cryosat2/2019/20190127:

/work2/noaa/ng-godas/jhossen/icefb_cryosat2/2019/20190128:

/work2/noaa/ng-godas/jhossen/icefb_cryosat2/2019/20190129:

/work2/noaa/ng-godas/jhossen/icefb_cryosat2/2019/20190130:

/work2/noaa/ng-godas/jhossen/icefb_cryosat2/2019/20190131:

**Comment by ShastriPaturi** [comment]
Pushed to r2d2 from 2019-01-01... 2019-01-26
