### ISSUE TITLE
ESA ice freeboard

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#404]
Process the same period as what was given by NESDIS

**Comment by mjhossen** [comment]
Ioda conversion is completed for the period of Oct 2018 to Mar 2019. @ShastriPaturi you can move them to the r2d2 database. Here is one of plots:
![Screen Shot 2022-10-27 at 3 19 12 PM](https://user-images.githubusercontent.com/65732322/198667781-3ec57f11-a9ff-4807-9c95-0e0b6d0b972f.png)

**Comment by ShastriPaturi** [comment]
@mjhossen can you share the path please?

**Comment by mjhossen** [comment]
Ioda converted  data is located in the folder: /work2/noaa/ng-godas/jhossen/icefb_cryosat_esa

**Comment by ShastriPaturi** [comment]
@mjhossen please rename the files as icefb_c2_esa_YYYYMMDD.nc

**Comment by mjhossen** [comment]
@ShastriPaturi Done

**Comment by ShastriPaturi** [comment]
Please save your files as YYYY/YYYYMMDD/icefb_c2_esa_YYYYMMDD.nc.
It is how the directory structure should be for pushing to R2D2. Thanks

**Comment by ShastriPaturi** [comment]
Converted data pushed to R2D2 for the period: 2018-10 to 2019-03.

**Comment by ShastriPaturi** [comment]
Completed.

**Comment by mjhossen** [comment]
@ShastriPaturi Ioda conversion is completed for the period of January 2020. Converted data is located at ```/work2/noaa/ng-godas/jhossen/icefb_cryosat_esa/2020```
Here is a plot for Jan 24, 2020:
![Screen Shot 2022-12-01 at 1 34 34 PM](https://user-images.githubusercontent.com/65732322/205133944-459d7ad5-d30b-4db8-9af2-7888f3f4edeb.png)
