### ISSUE TITLE
EMC5 run with p8

### ISSUE THREAD

**Issue by hyunchul386** [NOAA-EMC/godas#406]
EMC run for the period of  March 1st 2021 to May 31th 2021 with the ufs-weather-model of p8 
- same configurations with EMC-scout runs
- with the recent ufs-weather-model (2021-10-11, develop)

**Comment by guillaumevernieres** [comment]
@hyunchul386 , @ShastriPaturi , is this done? What was the context for that experiment again?

**Comment by ShastriPaturi** [comment]
@guillaumevernieres the period of the runs was to fill in the gap that was requested by Avichal.
@hyunchul386 can you please update and provide the path to your experiment? Do you have any plots for this period?
This is a deliverable.

**Comment by hyunchul386** [comment]
The run for filling the gap is emc5 in the period of 2021-03-01 ~ 2021-05-31, and the work directory is
/work/noaa/marine/Hyun-Chul.Lee/emc5.
I will prepare the slide.

**Comment by hyunchul386** [comment]
I will update the slide
