### ISSUE TITLE
Add polar stereo projection to EVA

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#407]
@mjhossen , I think what's below makes sense, but do adjust the wording if it does not.
- Pass the projection argument down the lower code levels
- Add the possibility of using polar stereo-graphic projections 

ps: Create an issue in the eva repository (https://github.com/JCSDA-internal/eva) before you start working on this problem.

**Comment by guillaumevernieres** [comment]
@mjhossen , looking at your latest figure, it looks like you are close to being able to create a PR in EVA? Did you create the issue in EVA as well?

**Comment by mjhossen** [comment]
Yes, I did. I will create a PR. Thanks.
