### ISSUE TITLE
S2S Initialization: Comparison of the multiple analysis streams

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#409]

**Comment by guillaumevernieres** [comment]
@hyunchul386 , could you link your google slides to this issue?

**Comment by hyunchul386** [comment]
Following is the link of slides
https://docs.google.com/presentation/d/1oRccNYFHNa7pSo0LkfFVjX5NIkiOnDf8ZmQ2C7ApnvE/edit#slide=id.p

**Comment by hyunchul386** [comment]
Just in case, would you let me know if there is difficulty to access the slide.

**Comment by guillaumevernieres** [comment]
All good @hyunchul386 . Thanks.
