### ISSUE TITLE
Evaluation of 3D BUMP at 1 deg

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#410]
## Description
Same as #301 but at 1 deg resolution

**Comment by guillaumevernieres** [comment]
@jieshunzhu , could you briefly document your 3DBUMP results here?

**Comment by jieshunzhu** [comment]
The link includes evaluations of 1deg 3D-BUMP run against EN4 for 1991 and Sep-Dec2019.
https://docs.google.com/presentation/d/1lqlc4BQhc6mr1pEa2PQhntI-xpIafykY/edit#slide=id.p16

The evaluations indicate that the 3D-BUMP run is much better than prior runs with soca-science release/stable-nightly branch during Mar-Jul (2D-BUMP). Their performance is comparable for the upper 300m ocean heat during Sep-Dec 2019. Except for that, the improvement is evident for all vertical section plots and for all plots for 1991. Compared to the 40-year reanalysis run, its performance for some plots is sightly degraded, but overall they seem to be comparable.
