### ISSUE TITLE
R2D2 on Hera

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#411]
# Description
Make a copy of the Orion r2d2 obs db on Hera for the period of 2021-03

## Currently a blocking issue for g-w dev

        Some progress:
![soca-in-g-w](https://user-images.githubusercontent.com/14031856/196811169-67f67271-90af-408e-b3f4-62d1801dc506.png)

It's currently only assimilating ADT, because that's all I have on Hera. It completed 1 cycle, including a coupled forecast with iau for mom6. :tada:

_Originally posted by @guillaumevernieres in https://github.com/NOAA-EMC/godas/issues/334#issuecomment-1284616707_

**Comment by ShastriPaturi** [comment]
R2D2 for 2021-03 (P1D and PT10M) are on hera:
/scratch2/NCEPDEV/marineda/r2d2/gdas_marine/ob/s2s_v1
