### ISSUE TITLE
[Bug] Localized unrealistic surface analysis

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#415]
## Description
As the title say, and we still don't understand why. It's time to get to the bottom of that issue before we start putting together other short reanalysis.

### Symptoms
- large omb's. _We're not necessarily too concerned about this, but it needs to be sorted out, probably by better calibrating **B**_ (@jieshunzhu is looking at it but at low-res)
- unrealistic sst gradients. _For lack of better words: sst "blobs" warmer than expected. It's concerning because @hyunchul386 's latest test still has this issue_ 
- unrealistically warm sst's in the high latitude. _Possibly related to the above, still an issue._

### Possible culprits
Ranked from very sus to less:
- interpolation
- B matrix
- IAU (the issue is not iau in mom6 but maybe how we use it)
- Forcing/model
- Observations

# Plan of action
Tentative todo list, to be revised 2022-11-02 and as we diagnose the issue(s).
- [x] Get clean IC’s. Spinup or whatever, we don't want to start with bad IC's
- [x] No DA run for ~10-15 days (TBD) to make sure the forcing isn't the cause of our troubles! (did we do that test already?)
- [x] Turn off IAU 

Remove all obs from the config except sst’s
- [x] Exp 1: Use the identity for B, run a few cycles. (@ShastriPaturi & @guillaumevernieres ) 
- [x] Exp 2: Use a simple B (saber Id + horiz-filt+vert-conv)
- [x] Analise differences between exp 1 and exp 2
- [ ] Exp 3: Depending on results of 1 & 2, add C (3D BUMP) only as static B (remove linear change of var)
- [ ] Analise differences
- [ ] Exp 4: Depending on 3 above, add the change of variables
- [ ] ...

**Comment by hyunchul386** [comment]
Just for short update,
- in comparison between with without iau run, there is no impact in UST (unrealistic surface temperature) in nothern polar region, but wihtout iau run makes the max temp capping as 33oC, in with iau has no that max temp cap.

**Comment by guillaumevernieres** [comment]
- Test with different forcing (CFSR, CORe and GFS)
- Look at @ShastriPaturi 's no DA and DA run that includes sea-ice obs (CORe)
- Time series of global OMB's for all obs

**Comment by hyunchul386** [comment]
Current evaluations and documentations

* SST bias in EMC_REF
* DA vs. no DA
* Surface forcing : CORe vs. CFSR
* with IAU vs. without IAU

**Comment by ShastriPaturi** [comment]
Plot of the background surface temp 2021081212 (before the model crash)
![image](https://user-images.githubusercontent.com/26145004/212184725-3f756301-e52e-4a24-a6f6-0b24d7c64cd2.png)

**Comment by guillaumevernieres** [comment]
Thanks @ShastriPaturi . It looks ugly but that was the point of that experiment!

**Comment by hyunchul386** [comment]
I am updating the slides for the my summary in daily base,
https://docs.google.com/presentation/d/1ggCb_h1tLJKGyY7CHJ0yRwHfXVWjqYAoMMAj2hwz8rQ/edit#slide=id.g1cfcd65e5c0_1_63

**Comment by guillaumevernieres** [comment]
BUG FOUND!!! Finally :) ... Thanks @ShastriPaturi for running all these 1 cycle exps.

**Comment by ShastriPaturi** [comment]
Thanks @guillaumevernieres for the help and working with me:
Tests with the background error parameterization:
SST increment from the BkgErrorGODAS:
![image](https://user-images.githubusercontent.com/26145004/212426093-1e88d3e6-815c-4c2b-9d1e-175566b90ef9.png)
Current set-up:
![image](https://user-images.githubusercontent.com/26145004/212426673-e96dd3f0-5980-4a48-ba94-a485d158d608.png)
![image](https://user-images.githubusercontent.com/26145004/212426837-bf4e43c2-7e5c-49ec-9b11-f0e9464b662c.png)

**Comment by liuxiao37k** [comment]
example sst bkg field from my long-term analysis (assimilating OSTIA only for sst, 24-hr da window, 20 months into the run):

<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/212445090-badc5b35-913c-45f1-8ebc-96930abf7341.png">

**Comment by guillaumevernieres** [comment]
@liuxiao37k , yes, what @ShastriPaturi shared above is a dramatic example of what could happen. Our default settings are not as bad, but we do see extreme values in our analysis regularly.

**Comment by guillaumevernieres** [comment]
We know what the issue is now, so closing!
