### ISSUE TITLE
Free forecast run with ufs-p8

### ISSUE THREAD

**Issue by hyunchul386** [NOAA-EMC/godas#417]
Free forecast run with ufs-p8 for the period of 2021-07-01 ~ 2021-11-30, 
which is the same one of the previous EMC_ref.
The history files are one our interval, for the DA testing.

**Comment by guillaumevernieres** [comment]
Is this done @hyunchul386 ?

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, @hyunchul386 can run with the p8_aug03 tag noda for the golden period.

**Comment by hyunchul386** [comment]
Yes, the work directory is /work/noaa/marine/Hyun-Chul.Lee/emc_ref_free and the history files are 
/work/noaa/marine/Hyun-Chul.Lee/emc_ref_free/SCRATCH/2021070106, etc

**Comment by hyunchul386** [comment]
This is from ufs develop branch of 2022-10-11

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres, @hyunchul386 can run with the p8_aug03 tag noda for the golden period.

We might decide to redo this run @ShastriPaturi , this was mainly done to provide history files that can be used by the GDASApp's stand alone application.
