### ISSUE TITLE
The number of processors at the JJOBs should be variable 

### ISSUE THREAD

**Issue by flampouris** [NOAA-EMC/godas#42]
Currently, the # processors at the JJOBS submitting scripts is hardcoded but should be variables, defined by the template at the workflow.

**Comment by jkuang-exploro** [comment]
Could you please point me to the specific file that need to updated?

**Comment by flampouris** [comment]
@JianKuang-NOAA we have hardcoded the number of processors at every JJOB file, e.g. [...]/jobs/JJOB_DA_3DVAR

Could you make it variable?

**Comment by jkuang-exploro** [comment]
Sure. Will do.

Jian

**Comment by flampouris** [comment]
It's the NPE variable at JJOBS defined at workflow/defaults/places.yaml
