### ISSUE TITLE
Static perturbations

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#428]
Generate a 30 member coupled forecast over ~1+year from which we will extract seasonally dependent perturbations.
The length of the forecast is t.b.d and will depend on how long it takes for the surface and upper ocean variance takes to saturate.

**Comment by liuxiao37k** [comment]
An ensemble of 30-member coupled forecasts (ufs p8 w/ BGC, 0.25deg) are currently running on machine gaea, initialized from a single ctrl run of marine analysis on 01/06/2019 w/ perturbations applied. Ensemble spreads are being monitored, and figures are routinely updated [here](https://docs.google.com/presentation/d/1-bBrAQJB4ViM6ap5_r3TFeePRI2uYRCh/edit?usp=sharing&ouid=111141640443068017057&rtpof=true&sd=true).

**Comment by guillaumevernieres** [comment]
Closing this @liuxiao37k. We'll create a new issue if there is a need for it.
