### ISSUE TITLE
Qualitative analysis of ESA's freeboard observations

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#440]
## Description
Investigate the quality of the retrieval compared to other estimates.
For example, compare to:
- NESDIS 
- ICESat-2
- CryoSat-2 from other centers
- ...

**Comment by mjhossen** [comment]
The following things I will do:

- Plot ESA ice freeboard for July to October 2021
- Compare this with NESDIS, ICESAT-2 and CryoSat2 (as mentioned above)

**Comment by mjhossen** [comment]
@guillaumevernieres and @ShastriPaturi I have completed the superobing of sea-ice freeboard of ESA. But the length is different for different days. That's why, I got an error message while calculating the mean/max for a month of data. 
The data is located in the folder:
```/work2/noaa/ng-godas/jhossen/icefb_cryosat_esa/superob/2021/```

**Comment by mjhossen** [comment]
Here is the plot of ICESat-2 (monthly) and IceBridge (daily). They are very different. 
![Screen Shot 2023-01-18 at 5 22 03 PM](https://user-images.githubusercontent.com/65732322/213308188-22fa9175-316a-41d8-b4d7-2b94dbeac42b.png)
![Screen Shot 2023-01-18 at 11 02 26 AM](https://user-images.githubusercontent.com/65732322/213308208-9479d517-288f-491f-a4a8-9ae5085dfca6.png)

**Comment by guillaumevernieres** [comment]
@mjhossen : Your icebridge plot does not look right, the icebridge data are quite sparse, just a few aircraft tracks. Where are the obs coming from and what did you do to create the figure?

**Comment by mjhossen** [comment]
@guillaumevernieres Thank you for finding the error. This is actually CryoSat-2 (Level-4 Sea Ice Elevation, Freeboard, and Thickness V001) available from 20 Sep 2010. I recheck the source.  The fact is the IceBridge data is only available until 25 April, 2013.  So, I cannot use it for the comparison.   
![Screen Shot 2023-01-18 at 9 18 06 PM](https://user-images.githubusercontent.com/65732322/213340042-b92ccf45-6746-490e-a302-01486daea514.png)

**Comment by mjhossen** [comment]
Here is the ESA ice freeboard (2021-10) monthly mean. The ESA is not comparable to IceSat-2 in the sense that freeboard height is much higher than the ESA. However, it looks like ESA is comparable to CryoSat-2. 

![Screen Shot 2023-01-20 at 5 05 41 PM](https://user-images.githubusercontent.com/65732322/213813659-83e33e15-a2ec-49e1-ab3a-adb22fa7f940.png)
![Screen Shot 2023-01-20 at 5 05 57 PM](https://user-images.githubusercontent.com/65732322/213813657-1d72181a-9431-4948-bed8-5a4fe8a2a383.png)
![Screen Shot 2023-01-20 at 5 05 11 PM](https://user-images.githubusercontent.com/65732322/213813662-b7170227-b27d-4f30-aa9c-a24ef83a0174.png)

**Comment by mjhossen** [comment]
![Screen Shot 2023-02-09 at 10 46 20 AM](https://user-images.githubusercontent.com/65732322/217940120-2d3633ac-8774-4d9f-a9c9-ae6f0864170d.png)
![Screen Shot 2023-02-09 at 4 07 44 PM](https://user-images.githubusercontent.com/65732322/217940124-f729e79c-1ad3-4986-8a39-67b591faf65d.png)

**Comment by ShastriPaturi** [comment]
Thanks @mjhossen. How are these comparable to ICESat-2 or other ice freeboard products?

**Comment by mjhossen** [comment]
@guillaumevernieres I have submitted a report on this issue. We can close it.
