### ISSUE TITLE
Check SST drifters IODA conversion

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/godas#468]
Check the IODA conversion of SST drifters for the JCSDA Golden period

**Comment by ShastriPaturi** [comment]
@liuxiao37k please update on what you are able to find with your current run for July 2021.

**Comment by liuxiao37k** [comment]
@ShastriPaturi @guillaumevernieres I confirm that the ioda conversion of drifter sst for July 2021 was incorrect (specifically, MetaData/time variable) such that my OSEs in which drifter data were included as a passive tracer did not produce the corresponding HofX in /obs_out. Unfortunately, I will need to rerun the HofX step once the drifter data are fixed.

**Comment by ShastriPaturi** [comment]
Thanks @liuxiao37k for confirming. I will work on getting the date fixed and let you know.

**Comment by liuxiao37k** [comment]
@ShastriPaturi I confirmed that the fixed drifter observations can be successfully read in H(x)/noda mode, at least for the golden period, except July 24 where there is no data.

**Comment by ShastriPaturi** [comment]
Thanks @liuxiao37k for confirming. I will add the July 24 dataset. Can you add the omb MAE plot you have and I can close this issue?

**Comment by liuxiao37k** [comment]
> Thanks @liuxiao37k for confirming. I will add the July 24 dataset. Can you add the omb MAE plot you have and I can close this issue?

@ShastriPaturi Yes! I will be working on the plots today and add the plots to both this issue and the OSE issue by COB today.

**Comment by liuxiao37k** [comment]
<img width="954" alt="Screen Shot 2023-04-20 at 1 55 40 PM" src="https://user-images.githubusercontent.com/2281138/233448832-c83f2689-5945-4207-9592-3691b4cb146c.png">

**Comment by liuxiao37k** [comment]
@ShastriPaturi confirming the OSEs' conclusion (consistent with the comparison against OSTIA), as well as that drifter data have been correctly fixed for the dates tested (July 1-18).
