### ISSUE TITLE
Rocoto Warnings 

### ISSUE THREAD

**Issue by flampouris** [NOAA-EMC/godas#47]
Since this morning, I get the message below, not sure what is the reason for it.

`[Stylianos.Flampouris@hfe03 workflowtest001]$ rocotorun -w workflow.xml -d workflow.db

09/27/19 12:08:18 UTC :: workflow.xml :: WARNING: Rocoto does not support Slurm's heterogeneous job feature.  However, Rocoto

09/27/19 12:08:18 UTC :: workflow.xml :: WARNING: does support Slurm requests for non-unifortm task geometries.  It does this by

09/27/19 12:08:18 UTC :: workflow.xml :: WARNING: converting non-uniform requests into the smallest uniform task geometry

09/27/19 12:08:18 UTC :: workflow.xml :: WARNING: request that can accommodate the non-uniform one during batch job submission.

09/27/19 12:08:18 UTC :: workflow.xml :: WARNING: It is up to the user to use the -m option of the srun command, or other

09/27/19 12:08:18 UTC :: workflow.xml :: WARNING: appropriate tools, in the job script to launch executables with an arbitrary

09/27/19 12:08:18 UTC :: workflow.xml :: WARNING: distribution of tasks.

09/27/19 12:08:18 UTC :: workflow.xml :: WARNING: Please see https://slurm.schedmd.com/faq.html#arbitrary for details
09/27/19 12:08:18 UTC :: workflow.xml :: WARNING: Rocoto has automatically converted '16:ppn=20+16:ppn=19' to '32:ppn=20' for this job
09/27/19 12:08:18 UTC :: workflow.xml :: WARNING: to facilitate the desired arbitrary task distribution.  Use
09/27/19 12:08:18 UTC :: workflow.xml :: WARNING: <nodes>32:ppn=20</nodes> in your workflow to eliminate this warning message.
[Stylianos.Flampouris@hfe03 workflowtest001]$ 
`

**Comment by jkuang-exploro** [comment]
This means that rocoto doesn't support heterogeneous job, where you have different cpu count across the nodes. In this case, you want 20 cpu per node for 16 of nodes, and 19 cpu per node for another 16 nodes. Instead, rocoto allocates you 20 cpu per node for 32 nodes.

We would need to change the resource to 32:ppn=20 to get rid of this message.
