### ISSUE TITLE
GEOS foundation temp

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#482]
Files from ops, provided by @danholdaway are here:
```/work/noaa/da/dholdawa/4g/geos_foundation_temperature_backgrounds```

Same process as for the `gfs`, intrep to mom6 grid, compare against ostia.

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres

- Any requests for the comparisons (each cycle, time aggregated, etc.), also vs. WCDA run
- Is there ostia already on the mom6 grid somewhere convenient?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres
> 
> * Any requests for the comparisons (each cycle, time aggregated, etc.), also vs. WCDA run
> * Is there ostia already on the mom6 grid somewhere convenient?

Sorry, just seeing this.

- OSTIA on MOM6 grid:

`/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/data/ostia/`
We might have a more official location.

- Comparison: For now, write the GEOS foundation temp interpolated to the mom6 grid to file.

**Comment by AndrewEichmann-NOAA** [comment]
On Hera in /scratch1/NCEPDEV/stmp4/Andrew.Eichmann/geos52mom6
