### ISSUE TITLE
HAT10 Vertical resolution

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#484]
## Description
Before we start interpolating @liuxiao37k 's global background error to the HAT10 domain, we need to make sure that the layer thicknesses are indeed not evolving in time.

## Work to do
A simple `ncdiff` of the MOM6 `h` field between restarts of 2 consecutive cycles. Make sure the `h` field difference is actually 0 everywhere.

**Comment by YongzuoLi-NOAA** [comment]
Thank you. I will look at MOM6 h.

**Comment by liuxiao37k** [comment]
The path is here:
gaea: /lustre/f2/dev/ncep/Xiao.Liu/sandbox/09aug2022/cpld_BGC_v2/ens2019010600_***

Please note that there are other experiments located under the same directory, but only the ones named ens2019010600_*** (*** = 001 to 030, n=30) are from this experiment.

**Comment by liuxiao37k** [comment]
@guillaumevernieres but why would we expect `h` not evolving with time in the fully coupled UFS? Wasn't it using a dynamic hybrid layer? I don't think the evolving `h` would be an issue, though, because I remapped all ensemble restart files to a static MOM.res.nc (static `h`) when I computed stddev. I then concatenated that static `h` to the stddev files. But, if @YongzuoLi-NOAA were to compute the HAT stddev directly from my ensemble runs, then yes, we need to pay attention to and treat the evolving `h`.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres but why would we expect `h` not evolving with time in the fully coupled UFS? Wasn't it using a dynamic hybrid layer? I don't think the evolving `h` would be an issue, though, because I remapped all ensemble restart files to a static MOM.res.nc (static `h`) when I computed stddev. I then concatenated that static `h` to the stddev files. But, if @YongzuoLi-NOAA were to compute the HAT stddev directly from my ensemble runs, then yes, we need to pay attention to and treat the evolving `h`.

It's for the regional @liuxiao37k , apparently they are running with z*.

**Comment by liuxiao37k** [comment]
> It's for the regional @liuxiao37k , apparently they are running with z*.

@guillaumevernieres oh I see. So this is to check `h` in the regional mom6 restarts...

**Comment by YongzuoLi-NOAA** [comment]
@liuxiao37k @guillaumevernieres Good morning, here are my command lines: h is varying with time 
#!/bin/bash

cd /work2/noaa/da/yongzuo/3DVAR_pfl

ln -sf SCRATCH/2022092112/ana_rst/ctrl/MOM.res.nc MOM.resA.nc
ln -sf rst/2022092118/ctrl/MOM.res.nc MOM.resB.nc

ncdiff -v h MOM.resA.nc MOM.resB.nc h.nc

ncdump -v h h.nc |more

data:

 h =
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 ............................................
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0.012525131647247, 0.0193591168585918, 0.0115124810282321,
    0.00354421602056654, -0.00831486539056847, -0.00889417938571846,

**Comment by guillaumevernieres** [comment]
I assume you did check visually as well @YongzuoLi-NOAA ?

**Comment by YongzuoLi-NOAA** [comment]
@guillaumevernieres Yes, here is plot at "1st Layer 5.05 m"
![h_diff5m](https://github.com/NOAA-EMC/godas/assets/83187935/ffc22f45-e3a5-4133-b1e7-1d1845ae8636)

**Comment by guillaumevernieres** [comment]
Did you check further down the water column @YongzuoLi-NOAA ?

**Comment by YongzuoLi-NOAA** [comment]
@guillaumevernieres I checked down and will provide plots.

**Comment by YongzuoLi-NOAA** [comment]
![diff_h](https://github.com/NOAA-EMC/godas/assets/83187935/edf5522a-a425-4d7c-b2b1-9126c824f02a)

**Comment by YongzuoLi-NOAA** [comment]
@guillaumevernieres Above is diff h at first 6 layers

**Comment by YongzuoLi-NOAA** [comment]
@guillaumevernieres soca/src/soca/LinearVariableChange/VertConv/soca_vertconv_mod.F90
       do j = nl, 1, -1
            do k = nl, 1, -1
              dist2 = abs(z(j)-z(k))
              coef = gc99(dist2/lz(k))
              field_dx%val(id,jd,k) = field_dx%val(id,jd,k) + coef*field_convdx%val(id,jd,j)
            end do
          end do

Either lz or sign inside gc99(dist2/lz(k)) makes vertical incr issue. It is easy to fix. (1) use fixed lz (2) use a simple Knorm*exp(-dist/L) with negative sign inside.

**Comment by YongzuoLi-NOAA** [comment]
./oops/src/oops/generic/gc99.cc
if (distnorm < 0.5) {
    gc99value = -8.0*pow(distnorm, 5.0)+8.0*pow(distnorm, 4.0)+5.0*pow(distnorm, 3.0)-
                20.0/3.0*pow(distnorm, 2.0)+1.0;
  } else if (distnorm < 1.0) {
    gc99value = 8.0/3.0*pow(distnorm, 5.0)-8.0*pow(distnorm, 4.0)+5.0*pow(distnorm, 3.0)+
                20.0/3.0*pow(distnorm, 2.0)-10.0*distnorm+4.0-1.0/(3.0*distnorm);
  } else {
    gc99value = DBL_EPSILON;
  }

**Comment by guillaumevernieres** [comment]
The use of `gc99` looks fine to me @YongzuoLi-NOAA .`lz_min` shouldn't be 0, so try with something that would make sense, like 20m.
