### ISSUE TITLE
rocotoviewer

### ISSUE THREAD

**Issue by flampouris** [NOAA-EMC/godas#63]
Check if the rocotoviewer is available on Hera, if ye describe how to use it.

**Comment by jkuang-exploro** [comment]
I've updated CROW so that a soft link to rocoto_viewer.py will be included in EXPDIR

**Comment by jkuang-exploro** [comment]
PR created for this inclusion, please check.

**Comment by flampouris** [comment]
I dont know how to use rocoto_view.py, please provide some instructions.
