### ISSUE TITLE
develop is broken

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#66]
@JianKuang-NOAA , did you revert your push from yesterday? 
Please, go in the setting and disallow direct pushes to develop, and set at least 1 approval to merge.
@flampouris , could you give it a shot as well. Unfortunate timing ...

**Comment by jkuang-exploro** [comment]
I did revert it.

Jian

**Comment by guillaumevernieres** [comment]
@JianKuang-NOAA , btw, for future reference, the revert should have been done through a PR, not a direct push to develop. I just did a fresh clone, still no go. 
Please issue your bug fix through a PR. 
The following commit works: 8b533c37ad446050a1760b6f1f02bc79515df639

**Comment by flampouris** [comment]
@guillaumeverieres what's the failing message?

**Comment by guillaumevernieres** [comment]
@flampouris is it working for you? I had to revert 1 or 2 commits to get back to a working version.
Here's the beginning of the traceback:

ERROR:crow.config:doc.platform.least_used_temp[0][0]: AttributeError error doc: no settings in ['user_places', 'accounting', 'platform_common', 'partition_
ERROR:crow.config:doc.platform.least_used_temp[0]: CalcKeyError error doc.platform.least_used_temp[0][0]: calc doc.settings.FIX_SCRUB - AttributeError
ERROR:crow.config:doc.platform.least_used_temp: CalcKeyError error doc.platform.least_used_temp[0][0]: calc doc.settings.FIX_SCRUB - AttributeError
[...]

**Comment by flampouris** [comment]
This is awkward, the FIX_SCRUB was introduced with Jian's PR, which I am
currently testing.

I will keep you posted.

**Comment by jkuang-exploro** [comment]
Yeah sorry again. 

The FIX_SCRUB feature is included in the updated PR of PR_ens branch. I've accidentally pushed it into the develop yesterday.

I've reverted one commit but it's possible that more than 1 commits need to be reverted.

I've set up the protection rule for develop. This will never happens.

**Comment by guillaumevernieres** [comment]
FIX_SCRUB was merged and is the last commit in develop ...

**Comment by guillaumevernieres** [comment]
> Yeah sorry again.
> 
> The FIX_SCRUB feature is included in the updated PR of PR_ens branch. I've accidentally pushed it into the develop yesterday.
> 
> I've reverted one commit but it's possible that more than 1 commits need to be reverted.
> 
> I've set up the protection rule for develop. This will never happens.

:+1: @JianKuang-NOAA , mistakes happen, you still don't come close to the number of blunders I have pushed to the various project I work on :)
If you scroll up, you'll see #tag of the last commit that worked for me.

**Comment by jkuang-exploro** [comment]
@guillaumevernieres 
@flampouris 
A bugfix PR has been created to revert the develop back to 8b533c3. Please check.

I've added the protection rule which will prevent this from happening again.

**Comment by flampouris** [comment]
Thank you Jian for taking care of this and it's good that you updated the
settings.

About the error, I was not working with the develop branch.

**Comment by guillaumevernieres** [comment]
> I've added the protection rule which will prevent this from happening again.
Perfect, that's something that any of us could do inadvertently. That's why I never do `git push` (hint hint @flampouris :) ) by itself, I make a habit of specifying the branch every time ... Too easy to make a mistake, more so when we multi-task with several projects. Which I know we all are!

**Comment by flampouris** [comment]
we are already ahead of this, closing.
