### ISSUE TITLE
The sst_prep_obs.sh is not compatible with staged and real time processing conversion

### ISSUE THREAD

**Issue by flampouris** [NOAA-EMC/godas#80]
The problem is more involved than it appears. 

For staged sst obs the sst_prep_obs.sh takes as an input the expected names of converted names. For converting the observations, the input is the path with the observations. 

Currently, the develop works for staged but it will fail -with one or the other way (filenames wrong, some obs not found, etc)- for not staged. From the other side the feature/Obs_Scripts will fail for the staged and will process successfully new observations.

**Comment by hyunchul386** [comment]
I guess, my issue would be related with this problem also, that is;

(may be related with ...
    142 --- Logging error ---
    143 Traceback (most recent call last):
    144   File "/scratch2/NCEPDEV/marine/Stylianos.Flampouris/save/anaconda3/lib/python3.7/logging/handlers.py", line 939, in emit
    145     self.socket.sendto(msg, self.address)
    146 OSError: [Errno 101] Network is unreachable
...)

And, got followings,

    178 + echo There are no SST observations from sst.gmi_l3u.ghrsst for 2011100112
    179 There are no SST observations from sst.gmi_l3u.ghrsst for 2011100112

even, the sst data is reading "20111001000000-REMSS-L3U_GHRSST-SSTsubskin-WSAT-wsat_20111001v7.0.1-v02.0-fv01.0.nc" by gds2_sst2ioda.py.

**Comment by flampouris** [comment]
It's on the Wiki. The Errno 101 is an error related to the diagnostics.
Check the output directory, the ioda file is present.

**Comment by hyunchul386** [comment]
In my case, 

    193 SST SOURCE = sst.avhrr19_l3u.nesdis
    194 obsrundir: /scratch1/NCEPDEV/stmp2/Hyun-Chul.Lee/Hyun-Chul.Lee/Hyun-Chul.Lee/rundir/workflowtest002/2011100112/Data/2011100112
    195 obsrundir: /scratch1/NCEPDEV/stmp2/Hyun-Chul.Lee/Hyun-Chul.Lee/Hyun-Chul.Lee/rundir/workflowtest002/2011100112/Data/2011100112
    196 + echo There are no SST observations from sst.avhrr19_l3u.nesdis for 2011100112
    197 There are no SST observations from sst.avhrr19_l3u.nesdis for 2011100112
    198 + set +x

but, sst.viirs_l3u.nesdis in /scratch2/NCEPDEV/marine/marineda/ocean_observations/data
has data for 2011100112.

Similar massages came from all SST data, and there is no ioda_sst, but only ioda_profile and ioda_adt data in the obsrundir.

**Comment by flampouris** [comment]
I see, you are trying to process the observations. The AVHRR obs will be
created correctly as soon as the PR #78 goes through. For now, you can use
the prestaged obs.

**Comment by ShastriPaturi** [comment]
Addressed the issue in the PR
