### ISSUE TITLE
parallel operation for non-parallel access in da_prep_soca

### ISSUE THREAD

**Issue by hyunchul386** [NOAA-EMC/godas#81]
task da_prep_soca has 10 nodes and io_fld_write has some inconsistency in non-parallel acess, like

     35 NOTE from PE     0: close_param_file: INPUT_MOM6/MOM_input has been closed successfully.
     36 NOTE from PE     0: close_param_file: INPUT_MOM6/MOM_override has been closed successfully.
     37 !!! ABORT in io_fld_write on task #0064: NetCDF: Parallel operation on file opened for non-parallel access
     38 application called MPI_Abort(MPI_COMM_WORLD, 1) - process 63
     39 srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
     40 slurmstepd: error: *** STEP 326934.0 ON h21c51 CANCELLED AT 2019-10-15T17:26:39 ***
     41 srun: error: h22c28: tasks 100-119: Killed

**Comment by guillaumevernieres** [comment]
@hyunchul386 : It doesn't look like you built the master branch of the soca-bundle.
