### ISSUE TITLE
CROW submodule updates to be communicated better

### ISSUE THREAD

**Issue by flampouris** [NOAA-EMC/godas#92]
Currently, CROW is a black box, we have to be aware of what's happening to that side.

**Comment by jkuang-exploro** [comment]
This type of confusion is normal when the system has reached certain level of complexity. The best solution is a intra-group workflow demonstration. I would like to do it at the first week of November.

**Comment by flampouris** [comment]
Hey @JianKuang-NOAA, ignore my messages till you are back! Focus on the new
member of the family and enjoy every moment!

I am just adding items to the todo list before, I forgot them.
